#!/usr/bin/env python3
"""Generate 'the ideas this page stands on' entry ramps for Phase 4 pages.

A ramp lists the prerequisite concepts a jump-in reader is assumed to have,
each with a one-line plain-language gloss and a link to the page that teaches
it properly. Terms come ONLY from tools/ramp_lexicon.json (hand-curated), so
noise cannot leak in. A term already taught earlier within Phase 4's own walk
is considered earned and never listed.

Idempotent: content between the RAMP:BEGIN / RAMP:END markers is regenerated;
everything else on the page is untouched. Run after content changes:

    python3 tools/build_ramps.py
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEX = json.loads((ROOT / "tools/ramp_lexicon.json").read_text())
MAX_TERMS, MIN_TERMS = 8, 3
BEGIN, END = "{/* RAMP:BEGIN generated by tools/build_ramps.py */}", "{/* RAMP:END */}"

docs = json.loads((ROOT / "docs.json").read_text())
order = []
def walk(n):
    if isinstance(n, dict):
        if n.get("hidden"): return
        [walk(n[k]) for k in ("groups","pages","tabs") if k in n]
    elif isinstance(n, list): [walk(x) for x in n]
    elif isinstance(n, str) and n not in order: order.append(n)
walk(docs["navigation"])
oidx = {s:i for i,s in enumerate(order)}

def beginner_text(raw):
    # ramp blocks are generated output, never source: exclude them from all scans
    raw = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), " ", raw, flags=re.S)
    out, skip = [], False
    for line in raw.splitlines():
        if re.search(r'<Tab title="[^"]*Layer [23]', line): skip = True
        elif skip and re.match(r'\s*</Tab>', line): skip = False; continue
        if not skip: out.append(line)
    t = re.sub(r"```.*?```", " ", "\n".join(out), flags=re.S)
    return re.sub(r"\{/\*.*?\*/\}", " ", t, flags=re.S)

# first page (reading order) that bolds each lexicon term = default target
first_bold = {}
for s in order:
    p = ROOT / (s + ".mdx")
    if not p.exists(): continue
    low = beginner_text(p.read_text()).lower()
    for m in re.finditer(r"\*\*([^*\n]{2,60})\*\*", low):
        t = m.group(1).strip().rstrip(".,:;").lower()
        t = t[:-1] if t.endswith("s") and t[:-1] in LEX else t
        if t in LEX and t not in first_bold: first_bold[t] = s

def target(term):
    t = LEX[term].get("target") or first_bold.get(term)
    return t if t and (ROOT / (t + ".mdx")).exists() else None

def week_label(slug, cur):
    m = re.search(r"week-(\d+)", slug)
    if not m: return "Taught earlier"
    wk = int(m.group(1))
    return (f"Coming in Week {wk}" if oidx.get(slug, 0) > oidx.get(cur, 0) else f"Taught in Week {wk}")

p4 = [s for s in order if s.startswith("curriculum/p4/")]
p4idx = {s:i for i,s in enumerate(p4)}
texts = {s: beginner_text((ROOT/(s+".mdx")).read_text()).lower() for s in p4 if (ROOT/(s+".mdx")).exists()}
bolds = {s: {(t[:-1] if t.endswith("s") and t[:-1] in LEX else t)
             for m in re.finditer(r"\*\*([^*\n]{2,60})\*\*", texts[s])
             for t in [m.group(1).strip().rstrip(".,:;").lower()]} for s in texts}

changed = skipped = 0
for s in p4:
    if s not in texts: continue
    earned = set().union(*(bolds[q] for q in texts if p4idx[q] <= p4idx[s]))
    hits = []
    for term in LEX:
        if term in earned: continue
        tgt = target(term)
        if not tgt or tgt == s: continue
        c = len(re.findall(r"\b" + re.escape(term) + r"s?\b", texts[s]))
        if c: hits.append((c, term, tgt))
    hits.sort(key=lambda x: (-x[0], x[1]))
    hits = hits[:MAX_TERMS]
    if len(hits) < MIN_TERMS: continue

    lines = [BEGIN,
      '<Accordion title="🧭 The ideas this page stands on — a 30-second refresher" icon="map">',
      "  Jumped straight here? Fair — this is the door many people enter through. This page leans",
      "  on a few ideas from earlier in the course. Each takes one line to hold in your head, and",
      "  links to the page that teaches it properly.", ""]
    for c, term, tgt in hits:
        lines.append(f"  - **{term}** — {LEX[term]['gloss']}. [{week_label(tgt, s)}](/{tgt})")
    lines += ["</Accordion>", END]
    block = "\n".join(lines)

    p = ROOT / (s + ".mdx"); raw = p.read_text()
    if BEGIN in raw:
        raw = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, raw, flags=re.S)
    elif "</Note>" in raw:
        raw = raw.replace("</Note>", "</Note>\n\n" + block, 1)
    elif "## Where this sits" in raw:
        raw = raw.replace("## Where this sits", block + "\n\n## Where this sits", 1)
    else:
        print(f"  SKIP (no anchor): {s}"); skipped += 1; continue
    p.write_text(raw); changed += 1

print(f"ramps written: {changed} pages, skipped: {skipped}, of {len(p4)} phase-4 pages")
