#!/usr/bin/env python3
"""Week-21 covers."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p3/week-21/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w21",
  "alt": "The week's journey: the bend that makes depth work, blame flowing backwards, reading a loss curve, momentum and dropout, and the library that remembers.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "the bend", "size": 17, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "why depth works", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "the blame", "size": 16, "color": "error"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "flows backwards", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "the curve", "size": 17, "color": "note"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "diagnose the run", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "the ball", "size": 17, "color": "correct"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "momentum · Adam", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "PyTorch", "size": 16, "color": "structure"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "arrays that remember", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 290, "y": 178, "w": 420, "h": 58, "label": "a network you trained and can debug", "size": 17, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 21", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "the machinery behind everything in Phase 4."},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with a problem no straight line can solve…", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-from-linear-models-to-neural-networks.mdx": {
  "id": "cover-w21m1",
  "alt": "Ticks in opposite corners cannot be split by any line; adding a bend between two layers curves the boundary; without the bend, a hundred layers collapse into one line.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "c1", "x": 130, "y": 68, "text": "✓", "size": 26, "color": "correct", "w": 999},
    {"type": "text", "id": "c2", "x": 250, "y": 68, "text": "✗", "size": 26, "color": "error", "w": 999},
    {"type": "text", "id": "c3", "x": 130, "y": 148, "text": "✗", "size": 26, "color": "error", "w": 999},
    {"type": "text", "id": "c4", "x": 250, "y": 148, "text": "✓", "size": 26, "color": "correct", "w": 999},
    {"type": "text", "id": "t1", "x": 190, "y": 200, "text": "separate them with ONE straight line", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 224, "text": "— you cannot. No angle works.", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "l1", "x": 425, "y": 44, "w": 80, "h": 40, "label": "line", "size": 14, "color": "structure"},
    {"type": "box", "id": "bd", "x": 515, "y": 44, "w": 80, "h": 40, "label": "bend", "size": 14, "color": "note"},
    {"type": "box", "id": "l2", "x": 605, "y": 44, "w": 80, "h": 40, "label": "line", "size": 14, "color": "structure"},
    {"type": "text", "id": "t2", "x": 555, "y": 118, "text": "the bend is one line of code:", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 555, "y": 140, "text": "keep positives, zero the rest", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2c", "x": 555, "y": 178, "text": "and now the boundary can curve ✓", "size": 16, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 214},
    {"type": "text", "id": "t3", "x": 840, "y": 228, "text": "no bend → 100 layers collapse", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 840, "y": 252, "text": "into a single straight line", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 262, "text": "activation", "ring": "note"},
    {"type": "note", "id": "n", "x": 360, "y": 250, "w": 290, "text": "a network is lines with bends between them. That is all."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "now: which of these thousands of numbers caused the error?", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-forward-pass-loss-backpropagation.mdx": {
  "id": "cover-w21m2",
  "alt": "Blame for a bad dish spreads back through chef, sous chef and supplier; the same chain rule sends each layer its share of the error in one backward sweep.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 60, "text": "a bad dish goes out.", "size": 17, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 88, "text": "whose fault?", "size": 17, "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 128, "text": "the chef · the sous chef ·", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 150, "text": "the tomato supplier", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1e", "x": 190, "y": 188, "text": "blame flows backwards along the chain", "size": 15, "color": "note", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "n1", "x": 425, "y": 44, "w": 90, "h": 40, "label": "layer 1", "size": 13, "color": "structure"},
    {"type": "box", "id": "n2", "x": 525, "y": 44, "w": 90, "h": 40, "label": "layer 2", "size": 13, "color": "structure"},
    {"type": "box", "id": "n3", "x": 625, "y": 44, "w": 110, "h": 40, "label": "prediction", "size": 13, "color": "correct"},
    {"type": "text", "id": "t2", "x": 570, "y": 116, "text": "forwards: one error number", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 570, "y": 152, "text": "backwards: each layer's share =", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2c", "x": 570, "y": 174, "text": "its own effect × the blame from ahead", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 210},
    {"type": "text", "id": "t3", "x": 858, "y": 222, "text": "one sweep · every parameter", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 248, "text": "roughly the cost of the forward pass", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the chain rule", "ring": "note"},
    {"type": "note", "id": "n", "x": 350, "y": 232, "w": 290, "text": "one small idea, applied over and over — and deep learning works."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "run it, and the loss goes to NaN. Now what?", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-training-dynamics.mdx": {
  "id": "cover-w21m3",
  "alt": "Four loss-curve shapes and their diagnoses: exploding, flat, overfitting, and healthy; the learning rate matters more than the architecture.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 60, "text": "the loss curve is the", "size": 17, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 88, "text": "patient's chart", "size": 17, "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 130, "text": "the first skill every", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 152, "text": "practitioner develops —", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1e", "x": 190, "y": 174, "text": "and it is not mathematical", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 378, "y": 108},
    {"type": "text", "id": "d1", "x": 572, "y": 62, "text": "shoots to infinity → steps too big", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "d2", "x": 572, "y": 92, "text": "flat from the start → no signal", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "d3", "x": 572, "y": 122, "text": "great, then validation rises → overfit", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "d4", "x": 572, "y": 152, "text": "noisy but descending → healthy ✓", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 682, "y": 216},
    {"type": "text", "id": "t3", "x": 838, "y": 214, "text": "the learning rate matters more", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 838, "y": 240, "text": "than the architecture everyone", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 838, "y": 266, "text": "argues about instead", "size": 16, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "reading the curve", "ring": "note"},
    {"type": "note", "id": "n", "x": 350, "y": 216, "w": 280, "text": "sweep the learning rate first. Change one thing at a time."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "everyone hit these — so the field built standard tools.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-optimizers-regularization-in-practice.mdx": {
  "id": "cover-w21m4",
  "alt": "A hiker feeling only the local slope stops in dips; a ball with momentum rolls through; Adam gives each parameter its own step size; dropout forces knowledge to spread.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "h", "x": 70, "y": 44, "w": 200, "h": 44, "label": "the hiker: local slope only", "size": 13, "color": "error"},
    {"type": "box", "id": "ball", "x": 70, "y": 98, "w": 200, "h": 44, "label": "the ball: carries speed", "size": 13, "color": "correct"},
    {"type": "text", "id": "t1", "x": 172, "y": 176, "text": "stops in every dip · zig-zags", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 172, "y": 200, "text": "rolls through · reaches the bottom ✓", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "adam", "x": 425, "y": 44, "w": 220, "h": 50, "label": "Adam", "size": 18, "color": "structure"},
    {"type": "text", "id": "t2", "x": 535, "y": 122, "text": "a step size per parameter —", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 535, "y": 144, "text": "steep slopes and flat ground", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2c", "x": 535, "y": 166, "text": "get different treatment", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2d", "x": 535, "y": 202, "text": "which is why it needs so little tuning", "size": 15, "color": "structure", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "box", "id": "dr", "x": 725, "y": 44, "w": 230, "h": 50, "label": "switch units off, at random", "size": 13, "color": "note"},
    {"type": "text", "id": "t3", "x": 840, "y": 122, "text": "sounds absurd — it stops the", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 840, "y": 144, "text": "network leaning on any one unit", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 840, "y": 182, "text": "a crowd, not an expert —", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3d", "x": 840, "y": 204, "text": "Week 18's lesson, again", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "momentum", "ring": "note"},
    {"type": "note", "id": "n", "x": 380, "y": 240, "w": 300, "text": "the cheapest improvements in the whole field."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "you have written every derivative by hand. Stop.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-pytorch-fundamentals.mdx": {
  "id": "cover-w21m5",
  "alt": "A tensor is a NumPy array that can live on a GPU and remembers how it was made, so the forward pass builds the graph that backward walks; the loop is five lines and one is always forgotten.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "t", "x": 70, "y": 44, "w": 210, "h": 44, "label": "a tensor", "size": 17, "color": "structure"},
    {"type": "text", "id": "t1", "x": 176, "y": 116, "text": "a NumPy array with two", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 176, "y": 138, "text": "extra powers:", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1c", "x": 176, "y": 172, "text": "1. it can live on a GPU", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t1d", "x": 176, "y": 196, "text": "2. it remembers how it was made", "size": 16, "color": "correct", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "text", "id": "g1", "x": 560, "y": 64, "text": "x · w  →  “I came from x and w”", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "g2", "x": 560, "y": 96, "text": "so the forward pass silently builds", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "g3", "x": 560, "y": 118, "text": "the graph backprop needs", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "g4", "x": 560, "y": 156, "text": ".backward() walks it for you", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "g5", "x": 560, "y": 190, "text": "you never write a derivative again", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 218},
    {"type": "text", "id": "t3", "x": 858, "y": 230, "text": "the loop is five lines — and the", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 254, "text": "forgotten one is zero_grad()", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "autograd", "ring": "note"},
    {"type": "note", "id": "n", "x": 360, "y": 232, "w": 290, "text": "without it, this batch's blame is added to the last one's."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and now: data where position means everything — pictures.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w21")
