#!/usr/bin/env python3
"""Week-17 covers."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p3/week-17/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w17",
  "alt": "The week's journey: what learning is, a line fitted by hand, a line that says yes or no, the dial that stops memorising, and the library the industry uses.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "the loop", "size": 17, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "guess · score · nudge", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "the line", "size": 17, "color": "correct"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "downhill in the fog", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "yes / no", "size": 17, "color": "note"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "squash it to 0–1", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "the dial", "size": 17, "color": "error"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "stop memorising", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "the library", "size": 16, "color": "structure"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "fit · predict · score", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 300, "y": 178, "w": 400, "h": 58, "label": "a model you built and can defend", "size": 18, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 17", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "machine learning, from the arithmetic up."},
    {"type": "text", "id": "dq", "x": 640, "y": 306, "text": "it starts with a rule nobody wrote down…", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-what-learning-from-data-actually-is.mdx": {
  "id": "cover-w17m1",
  "alt": "Five house prices let you guess a sixth without a formula; the machine does the same by guessing, scoring the error and nudging; the rule ends up inside a few numbers.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 92},
    {"type": "text", "id": "d1", "x": 190, "y": 58, "text": "50 m² → £150k · 70 → £210k", "size": 16, "w": 999},
    {"type": "text", "id": "d2", "x": 190, "y": 86, "text": "90 → £270k · 110 → £330k", "size": 16, "w": 999},
    {"type": "text", "id": "d3", "x": 190, "y": 126, "text": "100 m² → ?", "size": 20, "color": "correct", "w": 999},
    {"type": "text", "id": "t1", "x": 190, "y": 170, "text": "you said £300k without meaning to —", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 192, "text": "nobody gave you a formula", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "g", "x": 405, "y": 44, "w": 90, "h": 42, "label": "guess", "size": 14, "color": "structure"},
    {"type": "box", "id": "s", "x": 505, "y": 44, "w": 90, "h": 42, "label": "score", "size": 14, "color": "error"},
    {"type": "box", "id": "n2", "x": 605, "y": 44, "w": 90, "h": 42, "label": "nudge", "size": 14, "color": "correct"},
    {"type": "text", "id": "t2", "x": 550, "y": 116, "text": "repeat a few thousand times", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 684, "y": 158},
    {"type": "text", "id": "t3", "x": 848, "y": 164, "text": "the rule nobody wrote", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "t3b", "x": 848, "y": 190, "text": "now lives in a few numbers", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "t3c", "x": 848, "y": 224, "text": "those numbers are the model", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 230, "y": 250, "text": "learning", "ring": "note"},
    {"type": "note", "id": "n", "x": 380, "y": 200, "w": 300, "text": "no magic in the loop — a guess, an error, an adjustment."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "but which direction is “better”, and how far?", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-linear-regression-from-mathematical-scratch.mdx": {
  "id": "cover-w17m2",
  "alt": "Walking downhill in fog by feeling the slope is gradient descent; the exact one-step formula exists but needs a matrix inverse that grows with features, so almost nobody uses it.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 96},
    {"type": "text", "id": "t1", "x": 190, "y": 60, "text": "thick fog. You cannot see", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 84, "text": "the valley — but you can feel", "size": 16, "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 108, "text": "which way the ground slopes", "size": 16, "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 150, "text": "so step that way, and repeat", "size": 16, "color": "correct", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 352, "y": 54},
    {"type": "text", "id": "g1", "x": 560, "y": 68, "text": "gradient = the slope under your feet", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "g2", "x": 540, "y": 100, "text": "learning rate = how big a step", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "g3", "x": 540, "y": 138, "text": "too big → overshoot · too small → crawl", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "g4", "x": 540, "y": 176, "text": "this is how ChatGPT learned too", "size": 16, "color": "note", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 210},
    {"type": "box", "id": "ne", "x": 700, "y": 196, "w": 230, "h": 44, "label": "the exact one-step formula", "size": 14, "color": "structure"},
    {"type": "crossout", "id": "x", "x": 700, "y": 196, "w": 230, "h": 44, "style": "strike"},
    {"type": "text", "id": "t3", "x": 812, "y": 268, "text": "needs a matrix inverse — hopeless at scale", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 220, "text": "gradient descent", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 244, "w": 300, "text": "derive it once by hand and a hundred library calls make sense."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "now make that line answer “is this fraud?”", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-logistic-regression-classification.mdx": {
  "id": "cover-w17m3",
  "alt": "A straight line predicts an impossible 1.4 probability and is crossed out; a sigmoid squashes it into 0 to 1; turning 0.73 into an action is a business decision.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "bad", "x": 70, "y": 44, "w": 200, "h": 50, "label": "P(fraud) = 1.4", "size": 17, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 200, "h": 50, "style": "strike"},
    {"type": "text", "id": "t1", "x": 172, "y": 124, "text": "a straight line will happily", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 172, "y": 146, "text": "predict a 140% probability", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 350, "y": 62},
    {"type": "text", "id": "sg", "x": 500, "y": 74, "text": "keep the line — squash the output", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "sg2", "x": 500, "y": 106, "text": "big + → almost certainly yes", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "sg3", "x": 500, "y": 128, "text": "big − → almost certainly no", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "sg4", "x": 500, "y": 164, "text": "the sigmoid: any number → 0…1", "size": 16, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "box", "id": "p", "x": 715, "y": 44, "w": 240, "h": 46, "label": "P(fraud) = 0.73", "size": 16, "color": "note"},
    {"type": "text", "id": "t3", "x": 835, "y": 118, "text": "block it, or let it through?", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 835, "y": 154, "text": "the threshold is a business", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3c", "x": 835, "y": 176, "text": "decision, not a modelling one", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 220, "y": 246, "text": "logistic regression", "ring": "note"},
    {"type": "note", "id": "n", "x": 400, "y": 226, "w": 320, "text": "which mistake hurts more: fraud let through, or a customer wrongly accused?"},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "99% on the training data — and possibly worthless.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-regularization-the-bias-variance-trade-off.mdx": {
  "id": "cover-w17m4",
  "alt": "One student memorised every worked example and fails on new questions; another skimmed and knows too little; regularization is the dial between them.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "s1", "x": 70, "y": 44, "w": 210, "h": 46, "label": "memorised every example", "size": 14, "color": "error"},
    {"type": "text", "id": "t1", "x": 175, "y": 116, "text": "flawless on the book ·", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 175, "y": 138, "text": "lost when one number changes", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 175, "y": 172, "text": "overfitting", "size": 18, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 360, "y": 62},
    {"type": "box", "id": "s2", "x": 385, "y": 44, "w": 210, "h": 46, "label": "skimmed one summary page", "size": 14, "color": "structure"},
    {"type": "text", "id": "t2", "x": 490, "y": 116, "text": "calm about new questions ·", "size": 15, "color": "structure", "w": 999},
    {"type": "text", "id": "t2b", "x": 490, "y": 138, "text": "wrong about most of them", "size": 15, "color": "structure", "w": 999},
    {"type": "text", "id": "t2c", "x": 490, "y": 172, "text": "underfitting", "size": 18, "color": "structure", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "bar", "id": "d", "x": 760, "y": 54, "w": 150, "h": 20, "label": "the dial", "value": "λ", "color": "correct"},
    {"type": "text", "id": "t3", "x": 845, "y": 110, "text": "penalise eagerness — prefer", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3b", "x": 845, "y": 132, "text": "the simpler explanation", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3c", "x": 845, "y": 170, "text": "set it by the score on data", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3d", "x": 845, "y": 192, "text": "the model has never seen", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 220, "y": 246, "text": "regularization", "ring": "note"},
    {"type": "note", "id": "n", "x": 400, "y": 230, "w": 320, "text": "a perfect training score is not evidence of anything."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "you wrote every loop by hand. Nobody does that at work.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-scikit-learn-the-industry-surface.mdx": {
  "id": "cover-w17m5",
  "alt": "Hundreds of models share four verbs — fit, predict, transform, score; scaling before splitting leaks the test set and is crossed out; a pipeline makes that mistake structurally hard.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "v1", "x": 70, "y": 44, "w": 100, "h": 40, "label": "fit", "size": 16, "color": "correct"},
    {"type": "box", "id": "v2", "x": 180, "y": 44, "w": 110, "h": 40, "label": "predict", "size": 16, "color": "correct"},
    {"type": "box", "id": "v3", "x": 70, "y": 94, "w": 100, "h": 40, "label": "transform", "size": 14, "color": "correct"},
    {"type": "box", "id": "v4", "x": 180, "y": 94, "w": 110, "h": 40, "label": "score", "size": 16, "color": "correct"},
    {"type": "text", "id": "t1", "x": 178, "y": 168, "text": "hundreds of models,", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 178, "y": 190, "text": "one interface", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "leak", "x": 405, "y": 44, "w": 240, "h": 46, "label": "scale → then split", "size": 15, "color": "error"},
    {"type": "crossout", "id": "x", "x": 405, "y": 44, "w": 240, "h": 46, "style": "strike"},
    {"type": "text", "id": "t2", "x": 525, "y": 116, "text": "the test set leaks into training —", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2b", "x": 525, "y": 138, "text": "and your scores become fiction", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "box", "id": "pipe", "x": 715, "y": 44, "w": 240, "h": 46, "label": "Pipeline(scale → model)", "size": 14, "color": "correct"},
    {"type": "text", "id": "t3", "x": 835, "y": 118, "text": "fitted per fold — the mistake", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3b", "x": 835, "y": 140, "text": "becomes structurally hard", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3c", "x": 835, "y": 176, "text": "the best kind of safety", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 220, "y": 246, "text": "the estimator API", "ring": "note"},
    {"type": "note", "id": "n", "x": 400, "y": 230, "w": 320, "text": "swap a logistic regression for a forest: one line."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "some problems are not a slope — they are a flowchart.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w17")
