#!/usr/bin/env python3
"""Week-23 covers."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p3/week-23/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w23",
  "alt": "The week's journey: a model gains an address, is served properly, is packed into a container, deploys itself, and chooses between a rented machine and serverless.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "an address", "size": 15, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "notebook → service", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "serve it", "size": 17, "color": "correct"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "load once, validate", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "container", "size": 15, "color": "note"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "ship the machine", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "pipeline", "size": 16, "color": "correct"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "push → deployed", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "taxi?", "size": 17, "color": "structure"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "serverless or not", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 290, "y": 178, "w": 420, "h": 58, "label": "a model other software can rely on", "size": 17, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 23", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "a model in a notebook is not a product."},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with a brilliant employee who has no phone…", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-from-notebook-to-service.mdx": {
  "id": "cover-w23m1",
  "alt": "A notebook model has no address and dies with the session; a service gives it an endpoint and forces everything implicit to be written down.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "nb", "x": 70, "y": 44, "w": 220, "h": 70, "label": "brilliant · no phone · no desk", "size": 13, "color": "error"},
    {"type": "text", "id": "t1", "x": 180, "y": 142, "text": "it works only while you sit", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 180, "y": 164, "text": "beside it, and dies with the lid", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "svc", "x": 405, "y": 44, "w": 230, "h": 56, "label": "POST /predict", "size": 16, "color": "correct"},
    {"type": "text", "id": "t2", "x": 520, "y": 130, "text": "one conceptual change:", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 520, "y": 152, "text": "an address other software can call", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "text", "id": "t3", "x": 850, "y": 76, "text": "…and ten practical ones:", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 850, "y": 106, "text": "which model version is loaded", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3c", "x": 850, "y": 128, "text": "what a valid input is", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3d", "x": 850, "y": 150, "text": "what happens when it is not", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3e", "x": 850, "y": 172, "text": "and when 200 callers arrive at once", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the service", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 230, "w": 300, "text": "everything you did implicitly now has to be written down."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "so give it an address — carefully, because models are big.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-serving-with-fastapi.mdx": {
  "id": "cover-w23m2",
  "alt": "Loading the model inside the handler is crossed out at 2,000 ms per request; loading once at startup is 20 ms; validation and honest health checks come next.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "bad", "x": 70, "y": 44, "w": 230, "h": 52, "label": "load_model() inside the handler", "size": 12, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 230, "h": 52, "style": "strike"},
    {"type": "bar", "id": "b_1", "x": 130, "y": 116, "w": 180, "h": 18, "label": "load", "value": "2,000 ms", "color": "error"},
    {"type": "bar", "id": "b_2", "x": 130, "y": 150, "w": 8,   "h": 18, "label": "predict", "value": "20 ms", "color": "structure"},
    {"type": "text", "id": "t1", "x": 200, "y": 200, "text": "on every single request", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "good", "x": 425, "y": 44, "w": 230, "h": 52, "label": "load once, at startup", "size": 15, "color": "correct"},
    {"type": "text", "id": "t2", "x": 540, "y": 124, "text": "same code, two lines higher —", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 540, "y": 146, "text": "100× faster under load ✓", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 856, "y": 76, "text": "validate at the door —", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 856, "y": 98, "text": "a clear error, not a tensor trace", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 856, "y": 136, "text": "and a health check that knows", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3d", "x": 856, "y": 158, "text": "whether the model finished loading", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "load once", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 220, "w": 300, "text": "the code looks perfectly reasonable, and only fails under load."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "runs on your machine. Hand it over, and it breaks.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-docker.mdx": {
  "id": "cover-w23m3",
  "alt": "It works on my machine, so ship the machine; the image is cached layers, so dependencies go before code; and a multi-stage build turns 6 GB into 900 MB.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "joke", "x": 70, "y": 44, "w": 220, "h": 46, "label": "“it works on my machine”", "size": 14, "color": "error"},
    {"type": "box", "id": "fix", "x": 70, "y": 102, "w": 220, "h": 46, "label": "then ship the machine", "size": 15, "color": "correct"},
    {"type": "text", "id": "t1", "x": 180, "y": 180, "text": "code · Python · libraries ·", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 180, "y": 202, "text": "system packages · the model file", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "l1", "x": 410, "y": 44, "w": 200, "h": 30, "label": "base OS", "size": 12, "color": "structure"},
    {"type": "box", "id": "l2", "x": 410, "y": 80, "w": 200, "h": 30, "label": "python", "size": 12, "color": "structure"},
    {"type": "box", "id": "l3", "x": 410, "y": 116, "w": 200, "h": 30, "label": "dependencies", "size": 12, "color": "structure"},
    {"type": "box", "id": "l4", "x": 410, "y": 152, "w": 200, "h": 30, "label": "your code", "size": 12, "color": "note"},
    {"type": "text", "id": "t2", "x": 510, "y": 214, "text": "cached layers — order them wrong and", "size": 14, "color": "error", "w": 999},
    {"type": "text", "id": "t2b", "x": 510, "y": 236, "text": "every edit reinstalls everything", "size": 14, "color": "error", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "bar", "id": "s1", "x": 790, "y": 54, "w": 110, "h": 18, "label": "first try", "value": "6 GB", "color": "error"},
    {"type": "bar", "id": "s2", "x": 790, "y": 92, "w": 24,  "h": 18, "label": "multi-stage", "value": "900 MB", "color": "correct"},
    {"type": "text", "id": "t3", "x": 838, "y": 148, "text": "leave the compilers, tests", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3b", "x": 838, "y": 170, "text": "and the pip cache behind", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the container", "ring": "note"},
    {"type": "note", "id": "n", "x": 300, "y": 266, "w": 280, "text": "not a VM: it shares the kernel, and starts in a second."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "…but you still build it by hand, on your machine.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-ci-cd.mdx": {
  "id": "cover-w23m4",
  "alt": "A Friday deploy from a laptop with unrun tests is crossed out; a pipeline runs tests, builds and deploys on every push, and rolls back in three minutes.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "fri", "x": 70, "y": 44, "w": 230, "h": 62, "label": "Friday 6 p.m. · from a laptop · tests unrun", "size": 11, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 230, "h": 62, "style": "strike"},
    {"type": "text", "id": "t1", "x": 184, "y": 138, "text": "it was fine. It was fine four", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 184, "y": 160, "text": "more times. Then it was not.", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1c", "x": 184, "y": 196, "text": "discipline is a person —", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1d", "x": 184, "y": 218, "text": "and people have trains to catch", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "p1", "x": 425, "y": 44, "w": 100, "h": 40, "label": "test", "size": 13, "color": "correct"},
    {"type": "box", "id": "p2", "x": 535, "y": 44, "w": 100, "h": 40, "label": "build", "size": 13, "color": "correct"},
    {"type": "box", "id": "p3", "x": 645, "y": 44, "w": 100, "h": 40, "label": "deploy", "size": 13, "color": "correct"},
    {"type": "text", "id": "t2", "x": 570, "y": 112, "text": "on every push · identically", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 570, "y": 148, "text": "for a model service it also checks", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2c", "x": 570, "y": 170, "text": "that the model file still loads", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 200},
    {"type": "text", "id": "t3", "x": 858, "y": 212, "text": "deploys in 3 minutes →", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 238, "text": "rolls back in 3 minutes", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 840, "y": 268, "text": "a crisis becomes a nuisance", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 260, "text": "the pipeline", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 244, "w": 280, "text": "make the boring path automatic."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and you pay for that machine at 3 a.m. too.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-serverless-deployment.mdx": {
  "id": "cover-w23m5",
  "alt": "A rented server is a company car paid for around the clock; serverless is a taxi paid per trip; the catch for models is the cold start of several seconds.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "car", "x": 70, "y": 44, "w": 210, "h": 46, "label": "the company car", "size": 15, "color": "structure"},
    {"type": "text", "id": "t1", "x": 176, "y": 118, "text": "paid for every hour, including", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 176, "y": 140, "text": "the 14 nobody drives it", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1c", "x": 176, "y": 178, "text": "and if 40 people need a lift,", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1d", "x": 176, "y": 200, "text": "you have one car", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "taxi", "x": 405, "y": 44, "w": 210, "h": 46, "label": "the taxi", "size": 16, "color": "correct"},
    {"type": "text", "id": "t2", "x": 510, "y": 118, "text": "dormant costs nothing ·", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 510, "y": 140, "text": "10,000 requests → 10,000 taxis", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2c", "x": 510, "y": 178, "text": "no traffic overnight → no bill", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "bar", "id": "cs", "x": 790, "y": 54, "w": 160, "h": 18, "label": "cold", "value": "seconds", "color": "error"},
    {"type": "bar", "id": "wm", "x": 790, "y": 92, "w": 12,  "h": 18, "label": "warm", "value": "20 ms", "color": "correct"},
    {"type": "text", "id": "t3", "x": 856, "y": 144, "text": "boot · import · read a 400 MB", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 856, "y": 166, "text": "model — before the first answer", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the cold start", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 240, "w": 300, "text": "not ideology — arithmetic. Bursty and small: taxis."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and who decides how many copies run, and where?", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w23")
