#!/usr/bin/env python3
"""Week-24 covers — the last week of Phase 3."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p3/week-24/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w24",
  "alt": "The week's journey: declaring a desired state, a stable name over moving copies, limits and autoscaling, serving frameworks, and watching for drift.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "declare it", "size": 16, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "three copies, always", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "one name", "size": 16, "color": "correct"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "over moving parts", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "limits", "size": 17, "color": "error"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "and autoscaling", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "batching", "size": 16, "color": "correct"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "let the framework", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "drift", "size": 17, "color": "note"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "the silent failure", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 290, "y": 178, "w": 420, "h": 58, "label": "the end of the classical craft", "size": 18, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 24", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "running it is one thing. Operating it is another."},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with a container that died at 3 a.m…", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-why-orchestration-exists.mdx": {
  "id": "cover-w24m1",
  "alt": "A container dies at 3 a.m. with nothing watching; declaring three copies always makes a system responsible for restarting, rescheduling and rolling out.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "dead", "x": 70, "y": 44, "w": 210, "h": 50, "label": "container died · 03:14 Sunday", "size": 12, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 210, "h": 50, "style": "strike"},
    {"type": "text", "id": "t1", "x": 176, "y": 124, "text": "nobody noticed until Monday —", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 176, "y": 146, "text": "nothing was watching, and nothing", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 176, "y": 168, "text": "would have restarted it", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "want", "x": 405, "y": 44, "w": 240, "h": 50, "label": "“three copies, always”", "size": 16, "color": "correct"},
    {"type": "text", "id": "t2", "x": 525, "y": 124, "text": "you stop giving instructions", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 525, "y": 146, "text": "and start declaring an outcome", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2c", "x": 525, "y": 184, "text": "a system then keeps it true, forever", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 856, "y": 76, "text": "one dies → start another", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3b", "x": 856, "y": 100, "text": "a machine dies → move them", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3c", "x": 856, "y": 124, "text": "new version → one at a time", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3d", "x": 856, "y": 164, "text": "and sometimes one machine", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3e", "x": 856, "y": 186, "text": "is genuinely the right answer", "size": 15, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "desired state", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 232, "w": 300, "text": "a memory spike, a bad request, a kernel hiccup — it does not matter which."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "but how does traffic find copies whose addresses keep changing?", "size": 17, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-deployments-services-configuration.mdx": {
  "id": "cover-w24m2",
  "alt": "One stable name fronts copies that come and go; rolling updates check health before removing an old copy; secrets baked into an image are published to a registry.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "name", "x": 70, "y": 44, "w": 210, "h": 48, "label": "predict.internal", "size": 15, "color": "correct"},
    {"type": "text", "id": "t1", "x": 176, "y": 116, "text": "one fixed address for callers", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t1b", "x": 176, "y": 152, "text": "behind it: 10.2.4.19 · 10.2.7.31 ·", "size": 14, "color": "muted", "w": 999},
    {"type": "text", "id": "t1c", "x": 176, "y": 174, "text": "10.2.9.02 — all of them temporary", "size": 14, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "v1", "x": 405, "y": 44, "w": 70, "h": 40, "label": "v1", "size": 14, "color": "structure"},
    {"type": "box", "id": "v1b", "x": 485, "y": 44, "w": 70, "h": 40, "label": "v1", "size": 14, "color": "structure"},
    {"type": "box", "id": "v2", "x": 565, "y": 44, "w": 70, "h": 40, "label": "v2", "size": 14, "color": "correct"},
    {"type": "text", "id": "t2", "x": 520, "y": 112, "text": "one at a time · each proves it is", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 520, "y": 134, "text": "healthy before an old one goes", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2c", "x": 520, "y": 172, "text": "a deploy that drops no traffic ✓", "size": 16, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "box", "id": "sec", "x": 725, "y": 44, "w": 230, "h": 46, "label": "API key baked into the image", "size": 12, "color": "error"},
    {"type": "crossout", "id": "x", "x": 725, "y": 44, "w": 230, "h": 46, "style": "strike"},
    {"type": "text", "id": "t3", "x": 840, "y": 118, "text": "that is a secret published", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 840, "y": 140, "text": "to a registry", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3c", "x": 840, "y": 178, "text": "one image everywhere · settings", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3d", "x": 840, "y": 200, "text": "injected from outside ✓", "size": 15, "color": "correct", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the stable name", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 236, "w": 300, "text": "the copies come and go freely, and nobody outside notices."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "now: how big is each copy, and how many right now?", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-resources-scheduling-autoscaling.mdx": {
  "id": "cover-w24m3",
  "alt": "A container declared 2 GB and needs 3 is killed with nothing in the logs; and a model service's new copies arrive ninety seconds after the spike.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "bar", "id": "lim", "x": 200, "y": 52, "w": 120, "h": 20, "label": "you declared", "value": "2 GB", "color": "structure"},
    {"type": "bar", "id": "use", "x": 200, "y": 92, "w": 190, "h": 20, "label": "it needs", "value": "3 GB", "color": "error"},
    {"type": "text", "id": "t1", "x": 220, "y": 152, "text": "killed the instant it exceeds the limit —", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 220, "y": 174, "text": "and nothing in your logs says why", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 220, "y": 210, "text": "measure it, including the worst request", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 470, "y": 234},
    {"type": "text", "id": "t2", "x": 638, "y": 236, "text": "a web app scales in seconds", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 638, "y": 260, "text": "a model service takes ninety", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 856, "y": 76, "text": "so your new copies arrive", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 856, "y": 98, "text": "after the spike has passed", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3c", "x": 856, "y": 136, "text": "scale on leading signals ·", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3d", "x": 856, "y": 158, "text": "keep a warm floor ·", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3e", "x": 856, "y": 180, "text": "set generous cooldowns", "size": 15, "color": "correct", "w": 999},
    {"type": "circled", "id": "term", "x": 190, "y": 262, "text": "the OOM kill", "ring": "note"},
    {"type": "note", "id": "n", "x": 300, "y": 250, "w": 270, "text": "the platform believes you — and being wrong looks like a crash."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and somebody has already solved serving better than you.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-model-serving-frameworks.mdx": {
  "id": "cover-w24m4",
  "alt": "One request per GPU pass is a bus with one passenger; dynamic batching runs ten together for barely more cost; frameworks add versioning and GPU sharing.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 62, "text": "one request per GPU pass:", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 96, "text": "a bus route with one", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 118, "text": "passenger per bus", "size": 15, "color": "error", "w": 999},
    {"type": "bar", "id": "one", "x": 130, "y": 140, "w": 200, "h": 18, "label": "", "value": "10 × 20 ms", "color": "error"},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "bt", "x": 425, "y": 44, "w": 230, "h": 50, "label": "wait 3 ms · run them together", "size": 13, "color": "correct"},
    {"type": "bar", "id": "many", "x": 470, "y": 116, "w": 40, "h": 18, "label": "", "value": "≈ 24 ms for all ten ✓", "color": "correct"},
    {"type": "text", "id": "t2", "x": 540, "y": 176, "text": "3 ms of latency bought a large", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 540, "y": 198, "text": "multiple of throughput", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 856, "y": 76, "text": "also free: model versioning,", "size": 15, "color": "structure", "w": 999},
    {"type": "text", "id": "t3b", "x": 856, "y": 98, "text": "GPU sharing, metrics", "size": 15, "color": "structure", "w": 999},
    {"type": "text", "id": "t3c", "x": 856, "y": 136, "text": "the honest trade: another", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3d", "x": 856, "y": 158, "text": "system to operate, and less", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3e", "x": 856, "y": 180, "text": "freedom in your request path", "size": 15, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "dynamic batching", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 236, "w": 300, "text": "writing it yourself is possible, and unwise."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and then the failure no infrastructure prevents.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-operating-an-ml-service.mdx": {
  "id": "cover-w24m5",
  "alt": "Every dashboard is green while the input distribution shifts and accuracy decays; monitoring the data, not the service, is what catches drift.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "g1", "x": 190, "y": 58, "text": "uptime 99.98% ✓", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "g2", "x": 190, "y": 84, "text": "latency flat ✓", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "g3", "x": 190, "y": 110, "text": "zero errors ✓", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t1", "x": 190, "y": 154, "text": "…and the model is now", "size": 16, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 178, "text": "noticeably worse", "size": 16, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 214, "text": "nobody has a ticket: nothing failed", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 440, "y": 62},
    {"type": "text", "id": "d1", "x": 610, "y": 70, "text": "your customers are younger now", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "d2", "x": 610, "y": 94, "text": "a competitor changed pricing", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "d3", "x": 610, "y": 118, "text": "a supplier renamed a category", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "d4", "x": 610, "y": 156, "text": "the world moved; the model did not", "size": 16, "color": "error", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 194},
    {"type": "text", "id": "t3", "x": 838, "y": 208, "text": "monitor the DATA: input shape,", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3b", "x": 856, "y": 230, "text": "prediction mix, over time", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3c", "x": 838, "y": 264, "text": "then: retrain on what? who signs off?", "size": 14, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 190, "y": 262, "text": "drift", "ring": "note"},
    {"type": "note", "id": "n", "x": 300, "y": 234, "w": 280, "text": "a wrong answer returns 200 exactly like a right one."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "that is the end of Phase 3 — the black box opens next.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w24")
