#!/usr/bin/env python3
"""Week-29 covers — three-beat chapter maps."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p4/week-29/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w29",
  "alt": "The week's journey: the agent loop, tools it can call, memory it must manage, a standard plug for other people's tools, and a typed agent you can test.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "the loop", "size": 17, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "think · act · observe", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "tools", "size": 17, "color": "correct"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "it asks, you run", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "memory", "size": 17, "color": "note"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "what to forget", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "MCP", "size": 17, "color": "structure"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "one plug shape", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "typed", "size": 17, "color": "correct"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "software, not a script", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 300, "y": 178, "w": 400, "h": 58, "label": "an agent you would put on call", "size": 18, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 29", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "your friend stops answering and starts doing."},
    {"type": "text", "id": "dq", "x": 660, "y": 306, "text": "but most problems are recipes wearing a kitchen costume…", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-what-an-agent-actually-is.mdx": {
  "id": "cover-w29m1",
  "alt": "A recipe runs fixed steps and cannot handle a missing onion; a kitchen is handed over and decides for itself; the loop is think, act, observe, repeat.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "r1", "x": 70, "y": 44, "w": 200, "h": 40, "label": "chop → fry → plate", "size": 15, "color": "structure"},
    {"type": "text", "id": "t1", "x": 170, "y": 106, "text": "the recipe: same every time,", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 170, "y": 128, "text": "and it never sets fires", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1c", "x": 170, "y": 160, "text": "cannot handle a missing onion", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 350, "y": 62},
    {"type": "box", "id": "k", "x": 375, "y": 44, "w": 210, "h": 88, "label": "“make dinner” — the kitchen", "size": 15, "color": "note", "fill": "hachure", "fill_gap": 16},
    {"type": "text", "id": "t2", "x": 480, "y": 156, "text": "opens the fridge · walks to the shop", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 480, "y": 178, "text": "flexible · impossible to promise", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 680, "y": 62},
    {"type": "text", "id": "l1", "x": 850, "y": 72, "text": "the loop, entire:", "size": 16, "color": "muted", "w": 999},
    {"type": "text", "id": "l2", "x": 852, "y": 104, "text": "think → act → observe → repeat", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "l3", "x": 852, "y": 142, "text": "the model never runs anything —", "size": 15, "color": "structure", "w": 999},
    {"type": "text", "id": "l4", "x": 852, "y": 164, "text": "it only asks", "size": 15, "color": "structure", "w": 999},
    {"type": "circled", "id": "term", "x": 230, "y": 246, "text": "the agent loop", "ring": "note"},
    {"type": "note", "id": "n", "x": 420, "y": 228, "w": 350, "text": "most business problems are recipes wearing a kitchen costume."},
    {"type": "text", "id": "dq", "x": 640, "y": 306, "text": "a loop is only useful if it can DO something. Tools next.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-tools-function-calling.mdx": {
  "id": "cover-w29m2",
  "alt": "A vague tool card gets guessed calls and is crossed out; a precise schema gets the right call; validation stops an invented argument before it runs.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "bad", "x": 70, "y": 44, "w": 190, "h": 46, "label": "run(x) — “runs a thing”", "size": 14, "color": "error"},
    {"type": "crossout", "id": "x1", "x": 70, "y": 44, "w": 190, "h": 46, "style": "strike"},
    {"type": "box", "id": "good", "x": 70, "y": 106, "w": 220, "h": 54, "label": "get_order(id: str) — look up one order", "size": 12, "color": "correct"},
    {"type": "text", "id": "t1", "x": 178, "y": 190, "text": "the schema is the instruction manual", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "text", "id": "c1", "x": 545, "y": 70, "text": "model: “please run", "size": 17, "w": 999},
    {"type": "text", "id": "c2", "x": 545, "y": 96, "text": "get_order(TX-4471)”", "size": 17, "w": 999},
    {"type": "text", "id": "c3", "x": 545, "y": 134, "text": "your code: validate, then run", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "c4", "x": 545, "y": 166, "text": "you stay in charge — always", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 200},
    {"type": "text", "id": "d1", "x": 860, "y": 212, "text": "delete_customer(id)", "size": 16, "color": "error", "w": 999},
    {"type": "crossout", "id": "x2", "x": 760, "y": 196, "w": 200, "h": 26, "style": "strike"},
    {"type": "text", "id": "d2", "x": 848, "y": 246, "text": "destructive: a different category", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "d3", "x": 848, "y": 268, "text": "confirmed · idempotent · rare", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 220, "y": 250, "text": "function calling", "ring": "note"},
    {"type": "note", "id": "n", "x": 366, "y": 214, "w": 280, "text": "it will invent an argument eventually. Validate first."},
    {"type": "text", "id": "dq", "x": 600, "y": 306, "text": "ten minutes in, it forgets everything you said.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-memory-context-state.mdx": {
  "id": "cover-w29m3",
  "alt": "There is no memory: the whole transcript is re-sent every turn, so cost grows and the earliest instructions fall out of the window; three strategies keep, summarise or store.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t0", "x": 195, "y": 56, "text": "turn 50 re-sends turns 1–49", "size": 16, "w": 999},
    {"type": "bar", "id": "b_1", "x": 90, "y": 80, "w": 40,  "h": 16, "label": "", "value": "turn 1", "color": "structure"},
    {"type": "bar", "id": "b_2", "x": 90, "y": 112, "w": 120, "h": 16, "label": "", "value": "turn 20", "color": "structure"},
    {"type": "bar", "id": "b_3", "x": 90, "y": 144, "w": 210, "h": 16, "label": "", "value": "turn 50", "color": "error"},
    {"type": "text", "id": "t1", "x": 190, "y": 196, "text": "every turn costs more than the last", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "win", "x": 425, "y": 44, "w": 220, "h": 90, "label": "the context window", "size": 16, "color": "note"},
    {"type": "box", "id": "drop", "x": 425, "y": 146, "w": 150, "h": 40, "label": "turn 1: the rules", "size": 13, "color": "error"},
    {"type": "crossout", "id": "x", "x": 425, "y": 146, "w": 150, "h": 40, "style": "strike"},
    {"type": "text", "id": "t2", "x": 530, "y": 216, "text": "what falls out is usually what mattered", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "m1", "x": 850, "y": 72, "text": "keep the last N turns", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "m2", "x": 850, "y": 102, "text": "summarise the older ones", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "m3", "x": 838, "y": 132, "text": "store the rest, retrieve later", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "m4", "x": 838, "y": 168, "text": "(Week 27's library, inward)", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 240, "y": 250, "text": "there is no memory", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 262, "w": 320, "text": "memory design is really deletion design."},
    {"type": "text", "id": "dq", "x": 640, "y": 306, "text": "now plug it into everyone else's tools, without ten adapters.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-model-context-protocol-mcp.mdx": {
  "id": "cover-w29m4",
  "alt": "Three bespoke adapters for the same tool are crossed out; one agreed plug shape replaces them; and the trust warning: a tool server is code you did not write.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "a1", "x": 70, "y": 44, "w": 90, "h": 36, "label": "adapter A", "size": 13, "color": "error"},
    {"type": "box", "id": "a2", "x": 70, "y": 90, "w": 90, "h": 36, "label": "adapter B", "size": 13, "color": "error"},
    {"type": "box", "id": "a3", "x": 70, "y": 136, "w": 90, "h": 36, "label": "adapter C", "size": 13, "color": "error"},
    {"type": "text", "id": "t1", "x": 250, "y": 76, "text": "…all for the same Jira", "size": 16, "color": "error", "w": 999},
    {"type": "crossout", "id": "x", "x": 66, "y": 40, "w": 100, "h": 136, "style": "strike"},
    {"type": "text", "id": "t1b", "x": 190, "y": 196, "text": "the drawer full of adapters", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "srv", "x": 425, "y": 44, "w": 200, "h": 56, "label": "tool server", "size": 17, "color": "correct"},
    {"type": "box", "id": "cli", "x": 425, "y": 122, "w": 200, "h": 56, "label": "your agent", "size": 17, "color": "structure"},
    {"type": "line", "id": "wire", "x1": 525, "y1": 100, "x2": 525, "y2": 122, "color": "note", "width": 4},
    {"type": "text", "id": "t2", "x": 525, "y": 210, "text": "one agreed plug shape — write it once", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "w1", "x": 855, "y": 76, "text": "a tool server is code", "size": 16, "color": "error", "w": 999},
    {"type": "text", "id": "w2", "x": 855, "y": 98, "text": "you did not write,", "size": 16, "color": "error", "w": 999},
    {"type": "text", "id": "w3", "x": 855, "y": 120, "text": "inside your agent's trust", "size": 16, "color": "error", "w": 999},
    {"type": "text", "id": "w4", "x": 855, "y": 158, "text": "its results enter your context", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "w5", "x": 855, "y": 180, "text": "as text the model will act on", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 230, "y": 250, "text": "MCP", "ring": "note"},
    {"type": "note", "id": "n", "x": 360, "y": 250, "w": 300, "text": "boring, and therefore valuable."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "it works — and it is still held together by strings and hope.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-pydantic-ai-typed-agents.mdx": {
  "id": "cover-w29m5",
  "alt": "A prompt in a string with hopeful parsing is crossed out; a declared output type is validated and retried automatically; injected dependencies let the agent be tested offline.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "s", "x": 70, "y": 44, "w": 210, "h": 78, "label": "a prompt string · a dict of functions · hopeful parsing", "size": 12, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 210, "h": 78, "style": "strike"},
    {"type": "text", "id": "t1", "x": 175, "y": 152, "text": "fine in a demo —", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 175, "y": 174, "text": "unpleasant at 3 a.m.", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 360, "y": 62},
    {"type": "box", "id": "ty", "x": 385, "y": 44, "w": 230, "h": 56, "label": "declare the output type", "size": 16, "color": "correct"},
    {"type": "text", "id": "t2", "x": 500, "y": 128, "text": "wrong shape → handed back", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 500, "y": 150, "text": "and retried automatically", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t2c", "x": 500, "y": 186, "text": "the model is just another", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2d", "x": 500, "y": 208, "text": "untrusted boundary", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "box", "id": "test", "x": 715, "y": 44, "w": 240, "h": 56, "label": "run it against a fake model", "size": 15, "color": "structure"},
    {"type": "text", "id": "t3", "x": 835, "y": 128, "text": "offline · milliseconds · free", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "t3b", "x": 835, "y": 164, "text": "an agent you can put in CI", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 230, "y": 250, "text": "typed agents", "ring": "note"},
    {"type": "note", "id": "n", "x": 430, "y": 252, "w": 340, "text": "nothing about a language model makes ordinary engineering stop working."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "one agent, done well. Real work needs several — and they fail.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w29")
