#!/usr/bin/env python3
"""Week-18 covers."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p3/week-18/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w18",
  "alt": "The week's journey: a flowchart the machine wrote, a crowd of trees voting, boosting that learns from its own mistakes, groups nobody labelled, and the shadow that keeps the shape.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "one tree", "size": 17, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "a readable flowchart", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "a forest", "size": 17, "color": "correct"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "ask the crowd", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "boosting", "size": 16, "color": "note"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "fix your own errors", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "clusters", "size": 16, "color": "structure"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "no answer key", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "the shadow", "size": 15, "color": "correct"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "fewer dimensions", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 300, "y": 178, "w": 400, "h": 58, "label": "the models that win on real tables", "size": 17, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 18", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "not every pattern is a slope. Some are flowcharts."},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with how a loan officer really decides…", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-decision-trees.mdx": {
  "id": "cover-w18m1",
  "alt": "A loan decision as a sequence of questions; the machine picks each question by trying them all and keeping the tidiest split; unstopped, it grows a branch per customer.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "q1", "x": 70, "y": 44, "w": 200, "h": 40, "label": "employed?", "size": 15, "color": "structure"},
    {"type": "box", "id": "q2", "x": 90, "y": 94, "w": 200, "h": 40, "label": "over a year?", "size": 15, "color": "structure"},
    {"type": "box", "id": "q3", "x": 110, "y": 144, "w": 200, "h": 40, "label": "deposit > 20%? → approve", "size": 13, "color": "correct"},
    {"type": "text", "id": "t1", "x": 190, "y": 216, "text": "no coefficients · no line —", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 238, "text": "a flowchart the machine wrote", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 372, "y": 108},
    {"type": "bar", "id": "p1", "x": 480, "y": 52, "w": 60,  "h": 18, "label": "messy split", "value": "bad", "color": "error"},
    {"type": "bar", "id": "p2", "x": 480, "y": 90, "w": 170, "h": 18, "label": "tidy split", "value": "best ✓", "color": "correct"},
    {"type": "text", "id": "t2", "x": 520, "y": 142, "text": "it tries every possible question", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 520, "y": 164, "text": "and keeps the tidiest", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 842, "y": 78, "text": "print it and hand it to a", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3b", "x": 842, "y": 100, "text": "regulator — they can follow it ✓", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3c", "x": 855, "y": 138, "text": "left alone it grows a branch", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3d", "x": 842, "y": 162, "text": "per customer: Week 17 again", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 210, "y": 268, "text": "decision tree", "ring": "note"},
    {"type": "note", "id": "n", "x": 420, "y": 226, "w": 320, "text": "the one model a human can follow all the way to the decision."},
    {"type": "text", "id": "dq", "x": 640, "y": 306, "text": "but shuffle a few rows and it changes its mind.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-bagging-random-forests.mdx": {
  "id": "cover-w18m2",
  "alt": "One jumpy tree changes its mind; hundreds of trees on different samples vote and the errors cancel; feature subsampling makes them disagree more, which is the point.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "one", "x": 70, "y": 44, "w": 200, "h": 46, "label": "one tree", "size": 16, "color": "error"},
    {"type": "text", "id": "t1", "x": 172, "y": 118, "text": "shuffle a few rows →", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 172, "y": 140, "text": "different questions, different answer", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 172, "y": 176, "text": "readable, but jumpy", "size": 16, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 360, "y": 62},
    {"type": "ellipse", "id": "v1", "cx": 430, "cy": 66, "rx": 28, "ry": 18, "label": "", "color": "correct"},
    {"type": "ellipse", "id": "v2", "cx": 490, "cy": 60, "rx": 28, "ry": 18, "label": "", "color": "correct"},
    {"type": "ellipse", "id": "v3", "cx": 550, "cy": 68, "rx": 28, "ry": 18, "label": "", "color": "correct"},
    {"type": "ellipse", "id": "v4", "cx": 610, "cy": 60, "rx": 28, "ry": 18, "label": "", "color": "correct"},
    {"type": "text", "id": "t2", "x": 520, "y": 118, "text": "hundreds of trees · each on a", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 520, "y": 140, "text": "different random sample", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2c", "x": 520, "y": 178, "text": "they vote — the errors cancel ✓", "size": 16, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 855, "y": 76, "text": "each split sees only some", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 855, "y": 98, "text": "of the features", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 855, "y": 136, "text": "sounds like sabotage —", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3d", "x": 855, "y": 158, "text": "makes them disagree more,", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3e", "x": 855, "y": 180, "text": "which is exactly the point", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 210, "y": 250, "text": "random forest", "ring": "note"},
    {"type": "note", "id": "n", "x": 420, "y": 236, "w": 320, "text": "ask 500 people how many sweets are in the jar."},
    {"type": "text", "id": "dq", "x": 640, "y": 306, "text": "the trees never learn from each other. What if they did?", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-gradient-boosting-xgboost.mdx": {
  "id": "cover-w18m3",
  "alt": "Each round trains a small tree on what is still wrong, the leftover error shrinks, and past some round it starts fitting noise — so the learning rate and early stopping matter most.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 96},
    {"type": "text", "id": "t1", "x": 190, "y": 60, "text": "a forest is a crowd.", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 84, "text": "boosting is one student,", "size": 16, "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 108, "text": "revising.", "size": 16, "w": 999},
    {"type": "text", "id": "t1d", "x": 180, "y": 152, "text": "look at what is still wrong,", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1e", "x": 180, "y": 174, "text": "and train a tree on that", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "bar", "id": "e1", "x": 500, "y": 52, "w": 170, "h": 16, "label": "round 1", "value": "big error", "color": "error"},
    {"type": "bar", "id": "e2", "x": 500, "y": 84, "w": 90,  "h": 16, "label": "round 2", "value": "less", "color": "note"},
    {"type": "bar", "id": "e3", "x": 500, "y": 116, "w": 40,  "h": 16, "label": "round 3", "value": "less", "color": "note"},
    {"type": "bar", "id": "e4", "x": 500, "y": 148, "w": 14,  "h": 16, "label": "round 200", "value": "tiny", "color": "correct"},
    {"type": "text", "id": "t2", "x": 540, "y": 196, "text": "the best model there is for tables", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 686, "y": 224},
    {"type": "text", "id": "t3", "x": 840, "y": 228, "text": "keep going and it hunts noise", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 840, "y": 252, "text": "so: small steps + stop early", "size": 16, "color": "correct", "w": 999},
    {"type": "circled", "id": "term", "x": 210, "y": 246, "text": "the residuals", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 244, "w": 300, "text": "each new tree exists to fix what the last ones missed."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "all of this needed labels. Most data has none.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-unsupervised-learning-clustering.mdx": {
  "id": "cover-w18m4",
  "alt": "Laundry sorted into piles nobody named; k-means assigns points to the nearest marker and moves the markers until nothing changes; it cannot tell you how many piles exist.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 180, "y": 60, "text": "tip the laundry on the bed", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 180, "y": 88, "text": "and start sorting —", "size": 16, "w": 999},
    {"type": "text", "id": "t1c", "x": 180, "y": 116, "text": "nobody handed you categories", "size": 16, "w": 999},
    {"type": "text", "id": "t1d", "x": 180, "y": 158, "text": "you have a million customers", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1e", "x": 180, "y": 180, "text": "and no idea which kinds exist", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "ellipse", "id": "c1", "cx": 500, "cy": 76, "rx": 46, "ry": 26, "label": "", "color": "correct"},
    {"type": "ellipse", "id": "c2", "cx": 600, "cy": 130, "rx": 46, "ry": 26, "label": "", "color": "structure"},
    {"type": "ellipse", "id": "c3", "cx": 490, "cy": 168, "rx": 46, "ry": 26, "label": "", "color": "note"},
    {"type": "text", "id": "t2", "x": 540, "y": 216, "text": "nearest marker · move the marker · repeat", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 855, "y": 76, "text": "how many piles should there be?", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 855, "y": 100, "text": "the algorithm will not say", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3c", "x": 855, "y": 140, "text": "it makes four tidy groups from", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3d", "x": 855, "y": 162, "text": "data that has none", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 210, "y": 250, "text": "k-means", "ring": "note"},
    {"type": "note", "id": "n", "x": 400, "y": 244, "w": 320, "text": "reading meaning into arbitrary piles is how this technique embarrasses people."},
    {"type": "text", "id": "dq", "x": 640, "y": 306, "text": "and with 200 columns, “near” stops meaning anything.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-dimensionality-reduction-representation.mdx": {
  "id": "cover-w18m5",
  "alt": "A chair's shadow stays recognisable at a good angle and becomes a smudge at a bad one; PCA picks the angle; that is what an embedding is.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 180, "y": 60, "text": "200 columns:", "size": 17, "w": 999},
    {"type": "text", "id": "t1b", "x": 180, "y": 92, "text": "every point is roughly the", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 180, "y": 114, "text": "same distance from every other", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1d", "x": 180, "y": 152, "text": "“nearest neighbour” quietly", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1e", "x": 180, "y": 174, "text": "becomes meaningless", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "good", "x": 410, "y": 44, "w": 150, "h": 66, "label": "good angle ✓", "size": 15, "color": "correct"},
    {"type": "box", "id": "bad", "x": 410, "y": 124, "w": 150, "h": 50, "label": "bad angle ✗", "size": 15, "color": "error"},
    {"type": "text", "id": "t2", "x": 490, "y": 208, "text": "throw away dimensions, keep the meaning", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "text", "id": "t3", "x": 850, "y": 76, "text": "PCA: keep the directions", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "t3b", "x": 850, "y": 100, "text": "the data actually varies along", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "t3c", "x": 850, "y": 142, "text": "and now you know what an", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3d", "x": 850, "y": 164, "text": "embedding is — Phase 4's map,", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3e", "x": 850, "y": 186, "text": "learned instead of computed", "size": 15, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 210, "y": 250, "text": "the shadow", "ring": "note"},
    {"type": "note", "id": "n", "x": 400, "y": 240, "w": 320, "text": "a flat shadow still says “chair” — if you chose the angle well."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "every model gives you a number. Is the number honest?", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w18")
