#!/usr/bin/env python3
"""Week-22 covers."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p3/week-22/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w22",
  "alt": "The week's journey: photos as numbers, the sliding window, training with augmentation, borrowing a pretrained network, and getting the model out of the notebook.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "pixels", "size": 17, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "a photo is a grid", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "the window", "size": 15, "color": "correct"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "slides everywhere", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "×20 data", "size": 16, "color": "note"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "augmentation", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "borrow it", "size": 16, "color": "correct"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "transfer learning", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "export", "size": 17, "color": "structure"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "leave the notebook", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 290, "y": 178, "w": 420, "h": 58, "label": "a model that sees — and ships", "size": 18, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 22", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "the data that made deep learning famous."},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with the fact that a photograph is a spreadsheet…", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-images-as-data-opencv.mdx": {
  "id": "cover-w22m1",
  "alt": "A cat photo is a grid of 0–255 brightness values; colour is three stacked grids; a 4MP photo is twelve million numbers, and OpenCV hands you BGR.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "img", "x": 70, "y": 44, "w": 190, "h": 110, "label": "a cat", "size": 18, "color": "structure"},
    {"type": "text", "id": "t1", "x": 168, "y": 186, "text": "to you: a cat", "size": 16, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 168, "y": 210, "text": "to the machine: a grid of numbers", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "text", "id": "g1", "x": 530, "y": 66, "text": "0 = black · 255 = white", "size": 16, "w": 999},
    {"type": "text", "id": "g2", "x": 530, "y": 100, "text": "colour = three grids stacked:", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "g3", "x": 530, "y": 124, "text": "red · green · blue", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "g4", "x": 530, "y": 162, "text": "a 4MP colour photo =", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "g5", "x": 530, "y": 184, "text": "12,000,000 numbers in a box", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 220},
    {"type": "text", "id": "t3", "x": 858, "y": 232, "text": "OpenCV hands you B-G-R,", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 256, "text": "so your cat comes out blue", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 258, "text": "pixels", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 226, "w": 300, "text": "every tool from Week 21 already applies — a network eats numbers."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "but a cat two pixels left is still a cat. Who tells the model?", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-convolutional-neural-networks.mdx": {
  "id": "cover-w22m2",
  "alt": "A fully connected layer over twelve million pixels is crossed out; one 3x3 window slides everywhere instead; stacked layers learn edges, then shapes, then objects.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "fc", "x": 70, "y": 44, "w": 210, "h": 50, "label": "connect every pixel", "size": 15, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 210, "h": 50, "style": "strike"},
    {"type": "text", "id": "t1", "x": 176, "y": 124, "text": "billions of parameters —", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 176, "y": 146, "text": "and it must learn “cat”", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 176, "y": 168, "text": "separately for every position", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "k", "x": 415, "y": 44, "w": 80, "h": 60, "label": "3×3", "size": 17, "color": "note"},
    {"type": "text", "id": "t2", "x": 560, "y": 74, "text": "nine numbers, slid across", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 560, "y": 98, "text": "the whole image", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t2c", "x": 540, "y": 140, "text": "learn a vertical edge once →", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2d", "x": 540, "y": 162, "text": "find it everywhere, free", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 200},
    {"type": "text", "id": "t3", "x": 858, "y": 212, "text": "edges → corners → textures", "size": 15, "color": "structure", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 236, "text": "→ shapes → faces and wheels", "size": 15, "color": "structure", "w": 999},
    {"type": "text", "id": "t3c", "x": 858, "y": 264, "text": "nobody designed that hierarchy", "size": 15, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "convolution", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 226, "w": 290, "text": "your eye does the same: small patches, moved around."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "now train it — with only ten thousand photos.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-training-a-cnn-properly.mdx": {
  "id": "cover-w22m3",
  "alt": "Ten thousand photos invite memorising; flips, rotations and crops multiply them; a flipped 2 breaks the label; and the GPU often waits on the CPU.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 100},
    {"type": "text", "id": "t1", "x": 196, "y": 60, "text": "10,000 photos sounds like a lot", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 180, "y": 96, "text": "to a model with millions of", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 180, "y": 118, "text": "parameters it is an invitation", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1d", "x": 180, "y": 140, "text": "to memorise", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "a1", "x": 410, "y": 44, "w": 68, "h": 44, "label": "flip", "size": 13, "color": "correct"},
    {"type": "box", "id": "a2", "x": 488, "y": 44, "w": 68, "h": 44, "label": "rotate", "size": 12, "color": "correct"},
    {"type": "box", "id": "a3", "x": 566, "y": 44, "w": 68, "h": 44, "label": "crop", "size": 13, "color": "correct"},
    {"type": "box", "id": "a4", "x": 644, "y": 44, "w": 68, "h": 44, "label": "bright", "size": 12, "color": "correct"},
    {"type": "text", "id": "t2", "x": 560, "y": 118, "text": "a cat rotated 7° is still a cat ✓", "size": 16, "color": "correct", "w": 999},
    {"type": "box", "id": "bad", "x": 470, "y": 140, "w": 200, "h": 44, "label": "a flipped “2” is not a 2", "size": 14, "color": "error"},
    {"type": "crossout", "id": "x2", "x": 470, "y": 140, "w": 200, "h": 44, "style": "strike"},
    {"type": "text", "id": "t2b", "x": 570, "y": 210, "text": "the transform must preserve the label", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 676, "y": 244},
    {"type": "text", "id": "t3", "x": 826, "y": 248, "text": "your GPU is often idle, waiting", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 826, "y": 272, "text": "on the CPU to decode images", "size": 15, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "augmentation", "ring": "note"},
    {"type": "note", "id": "n", "x": 300, "y": 252, "w": 280, "text": "make more photos out of the ones you have."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "meanwhile, someone already trained on 14 million photos.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-transfer-learning.mdx": {
  "id": "cover-w22m4",
  "alt": "Early layers learned vision itself so they stay frozen; only the final head is retrained; the result beats training from scratch with a fraction of the data.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 60, "text": "a radiologist and a botanist", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 84, "text": "share years of groundwork —", "size": 16, "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 108, "text": "how to see", "size": 16, "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 150, "text": "edges and textures are not “cat”", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t1e", "x": 190, "y": 172, "text": "features — they are VISION features", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "f1", "x": 425, "y": 44, "w": 62, "h": 46, "label": "❄", "size": 17, "color": "structure"},
    {"type": "box", "id": "f2", "x": 495, "y": 44, "w": 62, "h": 46, "label": "❄", "size": 17, "color": "structure"},
    {"type": "box", "id": "f3", "x": 565, "y": 44, "w": 62, "h": 46, "label": "❄", "size": 17, "color": "structure"},
    {"type": "box", "id": "hd", "x": 640, "y": 44, "w": 110, "h": 46, "label": "your head", "size": 13, "color": "correct"},
    {"type": "text", "id": "t2", "x": 570, "y": 118, "text": "freeze what they learned ·", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 570, "y": 140, "text": "retrain only the last step", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2c", "x": 570, "y": 178, "text": "1/100 of the data · 20 minutes ✓", "size": 16, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 216},
    {"type": "text", "id": "t3", "x": 858, "y": 228, "text": "unfreeze too eagerly and it", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 252, "text": "forgets what it knew", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "transfer learning", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 240, "w": 290, "text": "keeping years of someone else's compute."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "“what is it” is easy. Where is it? Which pixels?", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-beyond-classification-model-export.mdx": {
  "id": "cover-w22m5",
  "alt": "Classification says what, detection says where and how many, segmentation says which pixels; and export turns a notebook checkpoint into something a phone can run.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "c", "x": 70, "y": 44, "w": 200, "h": 40, "label": "classify: “cat”", "size": 14, "color": "structure"},
    {"type": "box", "id": "d", "x": 70, "y": 94, "w": 200, "h": 40, "label": "detect: where · how many", "size": 12, "color": "correct"},
    {"type": "box", "id": "s", "x": 70, "y": 144, "w": 200, "h": 40, "label": "segment: which pixels", "size": 12, "color": "note"},
    {"type": "text", "id": "t1", "x": 176, "y": 216, "text": "same convolutions underneath —", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 176, "y": 238, "text": "different heads, different labels", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "nb", "x": 405, "y": 44, "w": 230, "h": 56, "label": "model.pt + your Python", "size": 14, "color": "error"},
    {"type": "crossout", "id": "x", "x": 405, "y": 44, "w": 230, "h": 56, "style": "strike"},
    {"type": "text", "id": "t2", "x": 520, "y": 130, "text": "runs only where you are sitting", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2b", "x": 520, "y": 168, "text": "exported: a phone app · a C++", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2c", "x": 520, "y": 190, "text": "service · a browser ✓", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 210},
    {"type": "text", "id": "t3", "x": 858, "y": 222, "text": "shrinking it to fit a phone is", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 246, "text": "your first quantization —", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 858, "y": 268, "text": "it returns in Week 26", "size": 15, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 268, "text": "export", "ring": "note"},
    {"type": "note", "id": "n", "x": 300, "y": 258, "w": 280, "text": "a model in a notebook is not a product."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "it has no address. Nobody can call it. Week 23.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w22")
