#!/usr/bin/env python3
"""Shared cover rendering: a week's file supplies COVERS specs, this renders
them through the house sketch renderer and inlines them (see the cover rules in
PLAN/00-content-spec.md)."""
import re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from sketch import render  # noqa: E402

W, H = 1000, 340
BEGIN, END = "{/* HERO:BEGIN generated by tools/covers_lib.py */}", "{/* HERO:END */}"

def live_arrow(x1, y1, x2, y2, theme):
    col = "#f08c00" if theme == "light" else "#ffb84d"
    return (f'<path d="M{x1} {y1} L{x2} {y2}" fill="none" stroke="{col}" stroke-width="3.5" '
            f'stroke-dasharray="12 9" opacity="0.9">'
            f'<animate attributeName="stroke-dashoffset" from="42" to="0" dur="1.6s" repeatCount="indefinite"/></path>')

def mdx_safe(s):
    s = re.sub(r"<!--.*?-->", "", s, flags=re.S)
    s = re.sub(r"<style>(.*?)</style>", lambda m: "<style>{`"+m.group(1)+"`}</style>", s, flags=re.S).strip()
    s = re.sub(r'(<svg[^>]*?)\swidth="\d+"\sheight="\d+"', r'\1 width="100%"', s, count=1)
    return re.sub(r"\s*\n\s*", " ", s)

def build(covers):
    for slug, spec in covers.items():
        spec = dict(spec); arrow = spec.pop("arrow")
        spec.setdefault("width", W); spec.setdefault("height", H); spec["hide_title"] = True
        v = {}
        for theme in ("light", "dark"):
            svg = render(spec, theme).replace("</svg>", live_arrow(*arrow, theme) + "</svg>")
            v[theme] = mdx_safe(svg)
        block = (f'{BEGIN}\n<Frame>\n  <div className="block dark:hidden w-full">\n    {v["light"]}\n  </div>'
                 f'\n  <div className="hidden dark:block w-full">\n    {v["dark"]}\n  </div>\n</Frame>\n{END}')
        p = ROOT / slug; t = p.read_text()
        old = re.search(r"\{/\* HERO:BEGIN[^}]*\*/\}.*?\{/\* HERO:END \*/\}", t, re.S)
        if old:
            t = t[:old.start()] + block + t[old.end():]
        else:
            i = t.index("<Note>") if "<Note>" in t else t.index("## ")
            t = t[:i] + block + "\n\n" + t[i:]
        p.write_text(t)
        print("  cover:", slug.split("/")[-1])

def preview(covers, tag):
    """Render each cover to /tmp/<tag>-<n>.png for visual review."""
    import subprocess
    for n, (slug, spec) in enumerate(covers.items(), 1):
        spec = dict(spec); spec.pop("arrow", None)
        spec.setdefault("width", W); spec.setdefault("height", H); spec["hide_title"] = True
        svg = render(spec, "light")
        f = f"/tmp/{tag}-{n}.svg"
        Path(f).write_text(svg)
        subprocess.run(["sips", "-s", "format", "png", f, "--out", f.replace(".svg", ".png")],
                       capture_output=True)
    print(f"  previews: /tmp/{tag}-1..{len(covers)}.png")
