#!/usr/bin/env python3
"""Covers for the prompting and agent-architecture weeks."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W29, W31 = "curriculum/p4/week-29/", "curriculum/p4/week-31/"
COVERS = {
W29+"index.mdx": {
  "id": "cover-w29",
  "alt": "The week's journey: say what you mean, show examples, send images when needed, budget the window, version the prompt, and diagnose failures.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 118, "h": 60, "label": "the note", "size": 16, "color": "structure"},
    {"type": "text", "id": "t1", "x": 139, "y": 126, "text": "say what you mean", "size": 14, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 248, "y": 60},
    {"type": "box", "id": "s2", "x": 273, "y": 40, "w": 112, "h": 60, "label": "examples", "size": 15, "color": "correct"},
    {"type": "text", "id": "t2", "x": 329, "y": 126, "text": "show, don't tell", "size": 14, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 435, "y": 60},
    {"type": "box", "id": "s3", "x": 460, "y": 40, "w": 112, "h": 60, "label": "images", "size": 16, "color": "note"},
    {"type": "text", "id": "t3", "x": 516, "y": 126, "text": "when it is not text", "size": 14, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 622, "y": 60},
    {"type": "box", "id": "s4", "x": 647, "y": 40, "w": 112, "h": 60, "label": "the window", "size": 14, "color": "error"},
    {"type": "text", "id": "t4", "x": 703, "y": 126, "text": "budget what it sees", "size": 14, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 809, "y": 60},
    {"type": "box", "id": "s5", "x": 834, "y": 40, "w": 124, "h": 60, "label": "versioned", "size": 15, "color": "correct"},
    {"type": "text", "id": "t5", "x": 896, "y": 126, "text": "prompts are code", "size": 14, "color": "muted", "w": 155},
    {"type": "box", "id": "res", "x": 290, "y": 178, "w": 420, "h": 58, "label": "the skill you use every working day", "size": 17, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 29", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "what “prompt engineer” jobs turned into: context engineering."},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with a colleague who has read everything…", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W29+"2-the-techniques-that-work.mdx": {
  "id": "cover-w29m2",
  "alt": "Six techniques with the decision table; the counter-example that teaches what an instruction cannot; and the two problems no technique solves.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 60, "text": "“Sort these into urgent", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 84, "text": "and ordinary.”", "size": 16, "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 124, "text": "some of it is wrong, and you", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 146, "text": "cannot say why — you never said", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1e", "x": 190, "y": 168, "text": "what urgent means to you", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "ex", "x": 425, "y": 44, "w": 300, "h": 44, "label": "“URGENT!!! When does the sale start?” → ORDINARY", "size": 10, "color": "correct"},
    {"type": "text", "id": "t2", "x": 575, "y": 116, "text": "the counter-example does the real work:", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 575, "y": 138, "text": "the word “urgent” is not being urgent", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2c", "x": 575, "y": 176, "text": "specificity · few-shot · think out loud ·", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2d", "x": 575, "y": 198, "text": "fences · contracts · roles · chaining", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 228},
    {"type": "text", "id": "t3", "x": 858, "y": 240, "text": "and two rows the table ends with:", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 264, "text": "missing facts → retrieval · habits → fine-tuning", "size": 14, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "few-shot", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 236, "w": 290, "text": "teach it the way you would teach a person."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "all of it competing for one finite window.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W29+"4-context-engineering.mdx": {
  "id": "cover-w29m4",
  "alt": "A single small desk holds the system prompt, tools, passages, history and question; when it is full something falls off and nothing tells you what.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "desk", "x": 70, "y": 60, "w": 230, "h": 100, "label": "one small desk", "size": 16, "color": "structure"},
    {"type": "text", "id": "t1", "x": 186, "y": 190, "text": "everything you want considered", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 186, "y": 212, "text": "must be placed on it first", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1c", "x": 186, "y": 248, "text": "and it will not tell you what fell off", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "text", "id": "c1", "x": 530, "y": 62, "text": "system prompt · examples ·", "size": 15, "w": 999},
    {"type": "text", "id": "c2", "x": 530, "y": 86, "text": "tool definitions · retrieved passages ·", "size": 15, "w": 999},
    {"type": "text", "id": "c3", "x": 530, "y": 110, "text": "history · the user's question", "size": 15, "w": 999},
    {"type": "text", "id": "c4", "x": 530, "y": 148, "text": "all competing, on every single call", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "c5", "x": 530, "y": 184, "text": "more is not better: extra material", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "c6", "x": 530, "y": 206, "text": "dilutes the passage that mattered", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 232},
    {"type": "text", "id": "t3", "x": 840, "y": 244, "text": "stable first · question last", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3b", "x": 840, "y": 268, "text": "answer space reserved ✓", "size": 14, "color": "correct", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 288, "text": "context engineering", "ring": "note"},
    {"type": "note", "id": "n", "x": 360, "y": 248, "w": 290, "text": "budget the window like money."},
    {"type": "text", "id": "dq", "x": 640, "y": 306, "text": "which makes it production logic, written in English.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W31+"index.mdx": {
  "id": "cover-w31",
  "alt": "The week's journey: four architectures, ReAct by hand, the harness, tool and context design, frameworks compared, and trajectory evaluation.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 118, "h": 60, "label": "4 shapes", "size": 16, "color": "structure"},
    {"type": "text", "id": "t1", "x": 139, "y": 126, "text": "ReAct · plan · reflect · team", "size": 13, "color": "muted", "w": 160},
    {"type": "badge", "id": "b2", "n": 2, "x": 248, "y": 60},
    {"type": "box", "id": "s2", "x": 273, "y": 40, "w": 112, "h": 60, "label": "by hand", "size": 16, "color": "correct"},
    {"type": "text", "id": "t2", "x": 329, "y": 126, "text": "60 lines, no framework", "size": 14, "color": "muted", "w": 155},
    {"type": "badge", "id": "b3", "n": 3, "x": 435, "y": 60},
    {"type": "box", "id": "s3", "x": 460, "y": 40, "w": 112, "h": 60, "label": "the harness", "size": 14, "color": "error"},
    {"type": "text", "id": "t3", "x": 516, "y": 126, "text": "seatbelts, not the engine", "size": 14, "color": "muted", "w": 155},
    {"type": "badge", "id": "b4", "n": 4, "x": 622, "y": 60},
    {"type": "box", "id": "s4", "x": 647, "y": 40, "w": 112, "h": 60, "label": "6 tools", "size": 16, "color": "note"},
    {"type": "text", "id": "t4", "x": 703, "y": 126, "text": "not forty drawers", "size": 14, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 809, "y": 60},
    {"type": "box", "id": "s5", "x": 834, "y": 40, "w": 124, "h": 60, "label": "score the path", "size": 13, "color": "correct"},
    {"type": "text", "id": "t5", "x": 896, "y": 126, "text": "not just the answer", "size": 14, "color": "muted", "w": 155},
    {"type": "box", "id": "res", "x": 290, "y": 178, "w": 420, "h": 58, "label": "an agent you would put on call", "size": 17, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 31", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "the loop is twenty lines. Everything else is why it survives."},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with four ways to send someone to the shops…", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W31+"3-the-harness.mdx": {
  "id": "cover-w31m3",
  "alt": "Two identical engines, one with seatbelts; six harness responsibilities; and the error message that is really a prompt.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 96},
    {"type": "text", "id": "t1", "x": 200, "y": 62, "text": "two cars, identical engines —", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 200, "y": 86, "text": "one has seatbelts and brakes", "size": 16, "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 126, "text": "on a test track they perform", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 148, "text": "the same. On a real road,", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1e", "x": 190, "y": 170, "text": "only one is a car.", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 390, "y": 62},
    {"type": "text", "id": "h1", "x": 545, "y": 62, "text": "validate the arguments", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "h2", "x": 545, "y": 86, "text": "keep turn · tile · time budgets", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "h3", "x": 545, "y": 110, "text": "turn exceptions into observations", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "h4", "x": 545, "y": 134, "text": "truncate tool output", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "h5", "x": 545, "y": 158, "text": "detect repeated calls", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "h6", "x": 545, "y": 182, "text": "record every step", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 218},
    {"type": "box", "id": "err", "x": 725, "y": 202, "w": 235, "h": 44, "label": "“Error”", "size": 15, "color": "error"},
    {"type": "crossout", "id": "x", "x": 725, "y": 202, "w": 235, "h": 44, "style": "strike"},
    {"type": "text", "id": "t3", "x": 828, "y": 272, "text": "“no order TX-4471 — ids look like AB-1234” ✓", "size": 12, "color": "correct", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 248, "text": "the harness", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 232, "w": 290, "text": "your error text goes back to the model — it is prompt engineering."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "hard to kill. Still only as good as its tools.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W31+"6-agent-evaluation-and-failure.mdx": {
  "id": "cover-w31m6",
  "alt": "Two runs reach the same answer, one in a single lookup and one in nine calls with a blocked refund; four numbers and four failure modes.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "a", "x": 70, "y": 44, "w": 210, "h": 40, "label": "run A: one lookup → correct ✓", "size": 12, "color": "correct"},
    {"type": "box", "id": "b", "x": 70, "y": 94, "w": 210, "h": 40, "label": "run B: 9 calls, a blocked refund → correct ✓", "size": 10, "color": "error"},
    {"type": "text", "id": "t1", "x": 176, "y": 170, "text": "score only the answer, and", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 176, "y": 192, "text": "these two are identical", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "text", "id": "n1", "x": 530, "y": 62, "text": "task success", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "n2", "x": 530, "y": 86, "text": "trajectory quality", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "n3", "x": 530, "y": 110, "text": "cost per SUCCESSFUL run", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "n4", "x": 530, "y": 134, "text": "safety of the path", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2", "x": 530, "y": 174, "text": "four numbers, and you need all four", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 208},
    {"type": "text", "id": "f1", "x": 858, "y": 220, "text": "repeated calls · compounding error ·", "size": 14, "color": "error", "w": 999},
    {"type": "text", "id": "f2", "x": 858, "y": 244, "text": "confident dead ends · silent partial success", "size": 14, "color": "error", "w": 999},
    {"type": "text", "id": "f3", "x": 858, "y": 272, "text": "the last two are invisible to answer-only scoring", "size": 13, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 246, "text": "trajectory", "ring": "note"},
    {"type": "note", "id": "n", "x": 350, "y": 224, "w": 290, "text": "a right answer by a terrible path is not a success."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and when one agent is not enough — Week 32.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w2931")
