#!/usr/bin/env python3
"""Week-10 covers. Content checked against the module pages: four layers,
TCP sequence/ACK/retransmission, socket lifecycle and short reads, framing and
heartbeats, public-key handshake and certificates."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p2/week-10/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w10",
  "alt": "The week's journey: wrapping a message in layers, choosing signed-for or a leaflet, answering the phone, agreeing where a message ends, and whispering in public.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "layers", "size": 17, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "envelopes in sacks", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "TCP / UDP", "size": 14, "color": "correct"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "signed-for, or a leaflet", "size": 15, "color": "muted", "w": 160},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "sockets", "size": 17, "color": "note"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "answering the phone", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "protocol", "size": 16, "color": "structure"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "where messages end", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "keys", "size": 17, "color": "correct"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "secrets in public", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 290, "y": 178, "w": 420, "h": 58, "label": "two machines that can trust each other", "size": 16, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 10", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "one machine was Week 9. Now make two agree."},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with a birthday card, an envelope and a sack…", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-the-network-stack.mdx": {
  "id": "cover-w10m1",
  "alt": "A card goes into an envelope into a sack onto a van; each network layer adds a header and treats the rest as opaque payload; the far end unwraps in reverse.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 40, "y": 154},
    {"type": "box", "id": "card", "x": 90, "y": 60, "w": 110, "h": 40, "label": "the card", "size": 13, "color": "correct"},
    {"type": "box", "id": "env", "x": 66, "y": 46, "w": 140, "h": 70, "label": "", "size": 12, "color": "note"},
    {"type": "box", "id": "sack", "x": 52, "y": 32, "w": 170, "h": 100, "label": "", "size": 12, "color": "structure"},
    {"type": "text", "id": "t1", "x": 196, "y": 172, "text": "card → envelope → sack → van", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 196, "y": 196, "text": "unwrapped in reverse at the far end", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "text", "id": "l1", "x": 560, "y": 66, "text": "your message", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "l2", "x": 560, "y": 94, "text": "+ app header", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "l3", "x": 560, "y": 122, "text": "+ TCP header", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "l4", "x": 560, "y": 150, "text": "+ IP header", "size": 16, "color": "muted", "w": 999},
    {"type": "text", "id": "t2", "x": 560, "y": 192, "text": "each header holds only what that layer needs", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 216},
    {"type": "text", "id": "t3", "x": 840, "y": 230, "text": "your app never learns whether", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 840, "y": 254, "text": "it went by fibre or Wi-Fi", "size": 15, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the header", "ring": "note"},
    {"type": "note", "id": "n", "x": 320, "y": 240, "w": 290, "text": "each layer deliberately ignorant of the others."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "nobody has promised it arrives at all.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-tcp-vs-udp.mdx": {
  "id": "cover-w10m2",
  "alt": "Signed-for post versus a leaflet; TCP numbers every byte and re-sends anything unacknowledged; and TCP delivers a byte stream, not your message boundaries.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "tcp", "x": 70, "y": 44, "w": 200, "h": 44, "label": "signed-for delivery", "size": 14, "color": "correct"},
    {"type": "box", "id": "udp", "x": 70, "y": 98, "w": 200, "h": 44, "label": "a leaflet through the door", "size": 12, "color": "note"},
    {"type": "text", "id": "t1", "x": 176, "y": 176, "text": "everything arrives, or you find out", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t1b", "x": 176, "y": 198, "text": "cheap, instant, nobody checks", "size": 15, "color": "note", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "text", "id": "r1", "x": 540, "y": 66, "text": "every byte gets a number", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "r2", "x": 540, "y": 94, "text": "“I have everything up to N”", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "r3", "x": 540, "y": 122, "text": "no ACK in time → send it again", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "t2", "x": 540, "y": 164, "text": "that is all reliability is — bookkeeping", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 540, "y": 200, "text": "for a live call, a packet from 2 s ago is useless", "size": 15, "color": "note", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 228},
    {"type": "text", "id": "t3", "x": 858, "y": 240, "text": "send “HELLO” then “WORLD” →", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 264, "text": "receive “HELLOWOR” then “LD”", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the byte stream", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 232, "w": 290, "text": "TCP never promised to keep your message boundaries."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "now write a program that actually uses it.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-socket-programming.mdx": {
  "id": "cover-w10m3",
  "alt": "A socket is a telephone: create, bind a number, listen, accept — each accepted call is its own line; and a short read returns less than you asked for.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "s1", "x": 190, "y": 60, "text": "get a phone", "size": 16, "w": 999},
    {"type": "text", "id": "s2", "x": 190, "y": 88, "text": "claim a number — bind", "size": 16, "w": 999},
    {"type": "text", "id": "s3", "x": 190, "y": 116, "text": "open for business — listen", "size": 16, "w": 999},
    {"type": "text", "id": "s4", "x": 190, "y": 144, "text": "wait for it to ring — accept", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t1", "x": 190, "y": 186, "text": "each accepted call is its own line;", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 208, "text": "the original phone stays free", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 440, "y": 62},
    {"type": "box", "id": "cl", "x": 465, "y": 44, "w": 200, "h": 46, "label": "the client: create · connect", "size": 12, "color": "structure"},
    {"type": "text", "id": "t2", "x": 565, "y": 118, "text": "much shorter — it is dialling,", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 565, "y": 140, "text": "not answering", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "box", "id": "sr", "x": 725, "y": 44, "w": 230, "h": 66, "label": "asked for 1,024 · got 300", "size": 14, "color": "error"},
    {"type": "text", "id": "t3", "x": 840, "y": 136, "text": "nothing failed — that is all", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 840, "y": 158, "text": "that had arrived by then", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3c", "x": 840, "y": 194, "text": "the bug appears under load —", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3d", "x": 840, "y": 216, "text": "which is to say, in production", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the short read", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 250, "w": 280, "text": "one send does not equal one receive."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "you can move bytes. Bytes are not a conversation.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-designing-an-application-protocol.mdx": {
  "id": "cover-w10m4",
  "alt": "A stream of letters with no punctuation cannot be split into messages; a delimiter or a length prefix supplies the boundary; a heartbeat proves someone is still there.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "raw", "x": 70, "y": 44, "w": 240, "h": 44, "label": "HELLOWORLDHOWAREYOU", "size": 12, "color": "error"},
    {"type": "text", "id": "t1", "x": 190, "y": 118, "text": "where does one message end?", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 140, "text": "bytes have no punctuation", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "d1", "x": 405, "y": 44, "w": 230, "h": 40, "label": "HELLO⏎  WORLD⏎", "size": 13, "color": "correct"},
    {"type": "box", "id": "d2", "x": 405, "y": 94, "w": 230, "h": 40, "label": "[5]HELLO  [5]WORLD", "size": 13, "color": "note"},
    {"type": "text", "id": "t2", "x": 520, "y": 162, "text": "a delimiter, or the length at the front", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 520, "y": 190, "text": "the length version tells the reader", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t2c", "x": 520, "y": 212, "text": "exactly how many bytes to collect ✓", "size": 15, "color": "note", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 856, "y": 76, "text": "a dead connection looks exactly", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 856, "y": 100, "text": "like a quiet one", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3c", "x": 856, "y": 138, "text": "so: a heartbeat — a small message", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3d", "x": 856, "y": 160, "text": "whose only job is to prove", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3e", "x": 856, "y": 182, "text": "someone is still there", "size": 15, "color": "correct", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "framing", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 240, "w": 290, "text": "design it on paper before you write a line of code."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and right now, anyone on the wire can read all of it.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-network-security-operations-basics.mdx": {
  "id": "cover-w10m5",
  "alt": "Two strangers agree a secret in a crowded room using a key pair; a certificate says whose key it is; and a fast shared key carries the real conversation.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 60, "text": "two strangers must agree", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 84, "text": "a password — out loud,", "size": 16, "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 108, "text": "in a crowded room", "size": 16, "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 150, "text": "it sounds impossible.", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t1e", "x": 190, "y": 174, "text": "it is not.", "size": 16, "color": "note", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "pub", "x": 425, "y": 44, "w": 210, "h": 42, "label": "public key — shouted", "size": 13, "color": "correct"},
    {"type": "box", "id": "priv", "x": 425, "y": 96, "w": 210, "h": 42, "label": "private key — never shared", "size": 12, "color": "structure"},
    {"type": "text", "id": "t2", "x": 530, "y": 170, "text": "what one locks, only the other opens —", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 530, "y": 192, "text": "so no secret needs arranging in advance ✓", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "box", "id": "cert", "x": 725, "y": 44, "w": 230, "h": 46, "label": "a certificate", "size": 15, "color": "note"},
    {"type": "text", "id": "t3", "x": 840, "y": 116, "text": "a public key + who it belongs to,", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 840, "y": 138, "text": "signed by an authority you trust", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 840, "y": 176, "text": "that signature is the whole basis", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3d", "x": 840, "y": 198, "text": "of “the padlock is showing”", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the key pair", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 236, "w": 300, "text": "slow maths once, to agree a fast key — then the real conversation."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "machines can talk. Now the maths everything else stands on.", "size": 17, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w10")
