#!/usr/bin/env python3
"""Week-9 covers. Facts checked against the module pages: NAND is functionally
complete; 16-bit two's complement runs -32768..+32767; the Hack ALU has six
control bits and the zr/ng flags."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p2/week-09/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w09",
  "alt": "The week's journey: switches become gates, gates become an adder, the adder becomes an ALU, feedback becomes memory, and together they run a program.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "gates", "size": 17, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "two switches, a bulb", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "adding", "size": 17, "color": "correct"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "1 + 1 makes a carry", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "the ALU", "size": 17, "color": "note"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "one box, many jobs", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "memory", "size": 17, "color": "structure"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "feedback + a clock", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "a program", "size": 15, "color": "correct"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "fetch · decode · execute", "size": 14, "color": "muted", "w": 165},
    {"type": "box", "id": "res", "x": 290, "y": 178, "w": 420, "h": 58, "label": "a computer you built from switches", "size": 17, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 9", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "no magic is left in the machine after this week."},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with two light switches and one bulb…", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-boolean-algebra-logic-gates.mdx": {
  "id": "cover-w09m1",
  "alt": "Two switches wired to a bulb make an AND gate; a truth table of four rows describes it completely; and one gate, NAND, can build all the others.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "sw1", "x": 70, "y": 44, "w": 100, "h": 40, "label": "switch a", "size": 13, "color": "structure"},
    {"type": "box", "id": "sw2", "x": 70, "y": 94, "w": 100, "h": 40, "label": "switch b", "size": 13, "color": "structure"},
    {"type": "box", "id": "bulb", "x": 200, "y": 68, "w": 90, "h": 44, "label": "bulb", "size": 14, "color": "correct"},
    {"type": "text", "id": "t1", "x": 180, "y": 168, "text": "lights only when BOTH are on", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t1b", "x": 180, "y": 192, "text": "— that is an AND gate", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "text", "id": "h", "x": 550, "y": 60, "text": "a    b    out", "size": 17, "color": "muted", "w": 999},
    {"type": "text", "id": "r1", "x": 550, "y": 88, "text": "0    0     0", "size": 17, "w": 999},
    {"type": "text", "id": "r2", "x": 550, "y": 114, "text": "0    1     0", "size": 17, "w": 999},
    {"type": "text", "id": "r3", "x": 550, "y": 140, "text": "1    0     0", "size": 17, "w": 999},
    {"type": "text", "id": "r4", "x": 552, "y": 166, "text": "1    1     1", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "t2", "x": 550, "y": 208, "text": "four rows describe it completely", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 858, "y": 76, "text": "and one gate — NAND —", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 100, "text": "can build all the others", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 858, "y": 138, "text": "not “in principle”:", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3d", "x": 858, "y": 160, "text": "you will do it on this page", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the truth table", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 240, "w": 300, "text": "a bit is a switch position. A gate is a wiring arrangement."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "but a computer must add. Nobody wired that in.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-combinational-arithmetic.mdx": {
  "id": "cover-w09m2",
  "alt": "1 plus 1 is binary 10, so a one-bit adder has two outputs; chained sixteen times the carry ripples; subtraction is a plus NOT b plus one.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 62, "text": "0+0 = 0    0+1 = 1", "size": 17, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 92, "text": "1+0 = 1", "size": 17, "w": 999},
    {"type": "text", "id": "t1c", "x": 194, "y": 128, "text": "1+1 = 10", "size": 20, "color": "note", "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 170, "text": "a digit that stays, and a", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1e", "x": 190, "y": 192, "text": "carry that moves left", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "a1", "x": 430, "y": 44, "w": 68, "h": 44, "label": "+", "size": 16, "color": "structure"},
    {"type": "box", "id": "a2", "x": 508, "y": 44, "w": 68, "h": 44, "label": "+", "size": 16, "color": "structure"},
    {"type": "box", "id": "a3", "x": 586, "y": 44, "w": 68, "h": 44, "label": "+", "size": 16, "color": "structure"},
    {"type": "box", "id": "a4", "x": 664, "y": 44, "w": 68, "h": 44, "label": "+", "size": 16, "color": "structure"},
    {"type": "text", "id": "t2", "x": 580, "y": 118, "text": "sixteen of them, side by side", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 580, "y": 148, "text": "the carry ripples along ←", "size": 16, "color": "note", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 186},
    {"type": "text", "id": "t3", "x": 858, "y": 198, "text": "a − b  =  a + NOT(b) + 1", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 226, "text": "no subtractor is ever built ✓", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3c", "x": 858, "y": 262, "text": "which is why 16 bits run −32,768…+32,767", "size": 14, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the carry", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 226, "w": 290, "text": "exactly what you do carrying a 1 when adding 7 + 5."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "now choose between operations, instruction by instruction.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-the-alu.mdx": {
  "id": "cover-w09m3",
  "alt": "Two 16-bit inputs and six control wires enter one box that computes many operations, and two status bits report whether the result was zero or negative.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 180, "y": 62, "text": "x[16]  and  y[16]  in", "size": 17, "w": 999},
    {"type": "text", "id": "t1b", "x": 180, "y": 96, "text": "+ six control wires", "size": 17, "color": "note", "w": 999},
    {"type": "text", "id": "t1c", "x": 180, "y": 138, "text": "flip them and the same", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1d", "x": 180, "y": 160, "text": "hardware does something else", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "text", "id": "o1", "x": 540, "y": 62, "text": "x + y", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "o2", "x": 540, "y": 90, "text": "x − y", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "o3", "x": 540, "y": 118, "text": "x AND y", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "o4", "x": 540, "y": 146, "text": "−1, or x unchanged, and more", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2", "x": 540, "y": 190, "text": "each control bit does one small thing:", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 540, "y": 212, "text": "zero an input · flip it · negate the output", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 856, "y": 76, "text": "zr — the result was zero", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 856, "y": 100, "text": "ng — the result was negative", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 856, "y": 140, "text": "two bits that look like an", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3d", "x": 856, "y": 162, "text": "afterthought — and are where", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3e", "x": 856, "y": 184, "text": "every if and loop begins", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the ALU", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 244, "w": 290, "text": "eighteen operations, one box, no duplicated circuits."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "fast, correct — and it forgets everything instantly.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-sequential-logic-memory-clock.mdx": {
  "id": "cover-w09m4",
  "alt": "Feeding an output back into its input lets a circuit hold a value; the clock restricts changes to the tick; a bit becomes a register becomes RAM.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 60, "text": "every circuit so far is", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 84, "text": "forgetful by design", "size": 16, "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 126, "text": "so how does a machine made", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 148, "text": "of them remember anything?", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "mem", "x": 430, "y": 44, "w": 200, "h": 56, "label": "output → back to input", "size": 13, "color": "note"},
    {"type": "text", "id": "t2", "x": 530, "y": 126, "text": "it feeds itself the same answer,", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t2b", "x": 530, "y": 148, "text": "over and over — that is memory", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t2c", "x": 530, "y": 186, "text": "made of the same gates as everything else", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 856, "y": 76, "text": "a loop like that is twitchy —", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 856, "y": 100, "text": "so a clock ticks 0,1,0,1 forever", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3c", "x": 856, "y": 124, "text": "and it may change only on the tick", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3d", "x": 856, "y": 164, "text": "1 cell = a bit · 16 = a register", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3e", "x": 856, "y": 186, "text": "many registers = RAM", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the clock", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 236, "w": 290, "text": "a heartbeat, and a rule that nothing moves in between."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "two halves on a table. What makes them run a program?", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-from-cpu-to-program.mdx": {
  "id": "cover-w09m5",
  "alt": "Some numbers in memory are instructions; the program counter says which is next; fetch, decode and execute repeat forever.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 100},
    {"type": "text", "id": "t1", "x": 200, "y": 60, "text": "memory holds numbers.", "size": 17, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 90, "text": "nothing about a number", "size": 16, "color": "muted", "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 112, "text": "says what it is for.", "size": 16, "color": "muted", "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 152, "text": "so: let some of them", "size": 17, "color": "note", "w": 999},
    {"type": "text", "id": "t1e", "x": 190, "y": 176, "text": "be instructions", "size": 17, "color": "note", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "f", "x": 425, "y": 44, "w": 90, "h": 40, "label": "fetch", "size": 14, "color": "structure"},
    {"type": "box", "id": "d", "x": 525, "y": 44, "w": 90, "h": 40, "label": "decode", "size": 13, "color": "note"},
    {"type": "box", "id": "e", "x": 625, "y": 44, "w": 90, "h": 40, "label": "execute", "size": 13, "color": "correct"},
    {"type": "text", "id": "t2", "x": 570, "y": 112, "text": "then move the program counter on,", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 570, "y": 134, "text": "and do it again — billions of times a second", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2c", "x": 570, "y": 178, "text": "you will hand-execute five of them", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2d", "x": 570, "y": 200, "text": "yourself — being the CPU", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 674, "y": 236},
    {"type": "text", "id": "t3", "x": 828, "y": 240, "text": "Python → instructions → gates", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 828, "y": 264, "text": "→ the switches you wired on Monday", "size": 15, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 190, "y": 258, "text": "fetch–decode–execute", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 216, "w": 290, "text": "programs are data. The machine reads them like anything else."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "one machine, alone. Now make two of them agree.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w09")
