#!/usr/bin/env python3
"""Week-19 covers."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p3/week-19/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w19",
  "alt": "The week's journey: accuracy that lies, the right yardstick per job, a split you can defend, the leak that ends careers, and a report a stakeholder can act on.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "99% ✗", "size": 17, "color": "error"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "accuracy lies", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "yardsticks", "size": 15, "color": "structure"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "three jobs, three", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "the split", "size": 17, "color": "correct"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "who grades you", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "leakage", "size": 17, "color": "error"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "the 0.99 that ends careers", "size": 15, "color": "muted", "w": 165},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "report it", "size": 17, "color": "note"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "read the failures", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 290, "y": 178, "w": 420, "h": 58, "label": "a number you can actually defend", "size": 18, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 19", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "every model gives you a number. This week: is it honest?"},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with a 99% accurate model that learned nothing…", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-classification-metrics.mdx": {
  "id": "cover-w19m1",
  "alt": "A 99% accurate fraud model that always answers no is crossed out; precision asks how many flags were real and recall asks how many frauds were caught; they trade off.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "acc", "x": 70, "y": 44, "w": 200, "h": 50, "label": "99.1% accurate", "size": 17, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 200, "h": 50, "style": "strike"},
    {"type": "text", "id": "t1", "x": 172, "y": 124, "text": "“always say not-fraud”", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 172, "y": 146, "text": "also scores 99%", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 172, "y": 182, "text": "1 in 100 is fraud", "size": 16, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 360, "y": 62},
    {"type": "text", "id": "p1", "x": 530, "y": 70, "text": "precision: of what you flagged,", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "p2", "x": 530, "y": 92, "text": "how much was real?", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "p3", "x": 530, "y": 126, "text": "recall: of the real frauds,", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "p4", "x": 530, "y": 148, "text": "how many did you catch?", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "p5", "x": 530, "y": 186, "text": "they pull against each other, always", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 676, "y": 224},
    {"type": "text", "id": "t3", "x": 832, "y": 226, "text": "low precision → angry customers", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 832, "y": 250, "text": "low recall → money out the door", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "precision · recall", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 240, "w": 300, "text": "which mistake can your business afford? Decide before you model."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and what if the model predicts a number, or a ranking?", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-regression-ranking-probabilistic-metrics.mdx": {
  "id": "cover-w19m2",
  "alt": "Squaring errors makes one four-hour delay dominate a thousand five-minute ones; ranking measures weight the top of the list; calibration asks whether 70% happens 70% of the time.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 180, "y": 62, "text": "1,000 orders wrong by 5 min", "size": 15, "w": 999},
    {"type": "text", "id": "t1b", "x": 180, "y": 88, "text": "1 order wrong by 4 hours", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 180, "y": 128, "text": "should that one dominate?", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t1d", "x": 180, "y": 164, "text": "square the errors → yes", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1e", "x": 180, "y": 186, "text": "treat them evenly → no", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "bar", "id": "r1", "x": 470, "y": 52, "w": 170, "h": 16, "label": "position 1", "value": "counts", "color": "correct"},
    {"type": "bar", "id": "r2", "x": 470, "y": 84, "w": 60,  "h": 16, "label": "position 5", "value": "a bit", "color": "note"},
    {"type": "bar", "id": "r3", "x": 470, "y": 116, "w": 8,   "h": 16, "label": "position 40", "value": "nobody scrolls", "color": "error"},
    {"type": "text", "id": "t2", "x": 520, "y": 166, "text": "ranking is graded at the top", "size": 16, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 200},
    {"type": "text", "id": "t3", "x": 850, "y": 212, "text": "“70% likely to churn”", "size": 17, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 850, "y": 240, "text": "do 70 of every 100 actually leave?", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3c", "x": 850, "y": 264, "text": "if not, it is a mood, not a probability", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "calibration", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 232, "w": 300, "text": "the choice of yardstick IS the business decision."},
    {"type": "text", "id": "dq", "x": 600, "y": 306, "text": "and which data gets to grade you at all?", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-validation-strategy.mdx": {
  "id": "cover-w19m3",
  "alt": "Grading on training data is marking your own exam; cross-validation rotates the held-out fold; random splits are a lie for time series and repeated subjects.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "own", "x": 70, "y": 44, "w": 210, "h": 50, "label": "graded on its training data", "size": 14, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 210, "h": 50, "style": "strike"},
    {"type": "text", "id": "t1", "x": 176, "y": 126, "text": "no school lets students write", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 176, "y": 148, "text": "and mark their own exam", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 360, "y": 62},
    {"type": "box", "id": "f1", "x": 390, "y": 44, "w": 52, "h": 34, "label": "exam", "size": 12, "color": "note"},
    {"type": "box", "id": "f2", "x": 448, "y": 44, "w": 52, "h": 34, "label": "train", "size": 12, "color": "structure"},
    {"type": "box", "id": "f3", "x": 506, "y": 44, "w": 52, "h": 34, "label": "train", "size": 12, "color": "structure"},
    {"type": "box", "id": "f4", "x": 564, "y": 44, "w": 52, "h": 34, "label": "train", "size": 12, "color": "structure"},
    {"type": "box", "id": "g1", "x": 390, "y": 88, "w": 52, "h": 34, "label": "train", "size": 12, "color": "structure"},
    {"type": "box", "id": "g2", "x": 448, "y": 88, "w": 52, "h": 34, "label": "exam", "size": 12, "color": "note"},
    {"type": "box", "id": "g3", "x": 506, "y": 88, "w": 52, "h": 34, "label": "train", "size": 12, "color": "structure"},
    {"type": "box", "id": "g4", "x": 564, "y": 88, "w": 52, "h": 34, "label": "train", "size": 12, "color": "structure"},
    {"type": "text", "id": "t2", "x": 500, "y": 156, "text": "every row gets a turn · average the scores", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "text", "id": "t3", "x": 850, "y": 76, "text": "random split on a time series →", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 850, "y": 98, "text": "you train on next week", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3c", "x": 850, "y": 136, "text": "random split on patients →", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3d", "x": 850, "y": 158, "text": "the same person sits both sides", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3e", "x": 850, "y": 196, "text": "split by time · split by group", "size": 16, "color": "correct", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "cross-validation", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 236, "w": 300, "text": "a beautiful score from a dishonest split is still a fiction."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and one failure walks straight past a perfect split.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-data-leakage-the-career-defining-failure-mode.mdx": {
  "id": "cover-w19m4",
  "alt": "A cancellation_reason column filled in only for customers who left produces a 0.99 score that is worthless in production; the habit is to ask whether each value exists at prediction time.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "auc", "x": 70, "y": 44, "w": 200, "h": 50, "label": "AUC = 0.99 🎉", "size": 17, "color": "correct"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 200, "h": 50, "style": "strike"},
    {"type": "text", "id": "t1", "x": 172, "y": 126, "text": "you have never seen a score", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 172, "y": 148, "text": "like it. You present on Thursday.", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 360, "y": 62},
    {"type": "box", "id": "col", "x": 385, "y": 44, "w": 250, "h": 56, "label": "cancellation_reason", "size": 15, "color": "error"},
    {"type": "text", "id": "t2", "x": 505, "y": 130, "text": "empty for everyone who stayed,", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2b", "x": 505, "y": 152, "text": "filled in for everyone who left", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2c", "x": 505, "y": 190, "text": "it read the answer off the back of the card", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "text", "id": "t3", "x": 850, "y": 76, "text": "the habit that prevents it:", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t3b", "x": 850, "y": 108, "text": "“would this value exist,", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t3c", "x": 850, "y": 130, "text": "with this content, at the", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t3d", "x": 850, "y": 152, "text": "moment I need the prediction?”", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t3e", "x": 850, "y": 192, "text": "validation cannot catch this", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "leakage", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 238, "w": 300, "text": "it arrives as unusually good news — the thing teams least like to challenge."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "0.91 or 0.92 — a win, or a coin flip?", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-model-selection-error-analysis-reporting.mdx": {
  "id": "cover-w19m5",
  "alt": "A 0.01 gap on 400 rows is inside the noise; reading the wrong answers reveals clusters like new customers and weekends; the report includes where it fails and for whom.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 180, "y": 62, "text": "model A: 0.91", "size": 18, "w": 999},
    {"type": "text", "id": "t1b", "x": 180, "y": 90, "text": "model B: 0.92", "size": 18, "color": "correct", "w": 999},
    {"type": "text", "id": "t1c", "x": 180, "y": 132, "text": "on 400 test rows, that gap is", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1d", "x": 180, "y": 154, "text": "comfortably inside the noise", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1e", "x": 180, "y": 190, "text": "a decision on a coin flip", "size": 16, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "e", "x": 405, "y": 44, "w": 240, "h": 50, "label": "read the rows it got wrong", "size": 15, "color": "correct"},
    {"type": "text", "id": "t2", "x": 525, "y": 124, "text": "20 minutes in, patterns appear:", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 525, "y": 150, "text": "new customers · weekends ·", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t2c", "x": 525, "y": 172, "text": "anything in a second language", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "t2d", "x": 525, "y": 206, "text": "no amount of tuning finds these", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "box", "id": "rep", "x": 725, "y": 44, "w": 230, "h": 56, "label": "the report", "size": 16, "color": "structure"},
    {"type": "text", "id": "t3", "x": 840, "y": 130, "text": "the score, the interval,", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3b", "x": 840, "y": 152, "text": "and where it fails, for whom", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "error analysis", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 244, "w": 290, "text": "the highest-value hour in ML, and almost nobody spends it."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "all of this assumed the columns you were given.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w19")
