#!/usr/bin/env python3
"""Week-11 covers. Arithmetic verified: [3,4] has length 5, [3,4]·[4,3]=24,
[3,4]·[-4,3]=0. Chain-rule example 2 x 3 = 6."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p2/week-11/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w11",
  "alt": "The week's journey: arrows and the dot product, matrices as actions, the directions that do not turn, slopes, and stepping downhill.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "arrows", "size": 17, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "where “similar” lives", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "matrices", "size": 16, "color": "correct"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "a grid that is a verb", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "skeleton", "size": 16, "color": "note"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "directions that hold", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "slopes", "size": 17, "color": "structure"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "how steep, right here", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "downhill", "size": 16, "color": "correct"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "the step size decides", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 290, "y": 178, "w": 420, "h": 58, "label": "the maths the rest of the course stands on", "size": 16, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 11", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "small, concrete, and taught with pictures."},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with two numbers on a piece of paper…", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-vectors-vector-spaces.mdx": {
  "id": "cover-w11m1",
  "alt": "The point 3 across and 4 up is an arrow of length 5; the dot product of [3,4] and [4,3] is 24, and with [-4,3] it is zero.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 62, "text": "3 across, 4 up:  [3, 4]", "size": 18, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 96, "text": "draw the arrow from the origin", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 134, "text": "it has a length (5) and it", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 156, "text": "points somewhere", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "text", "id": "d1", "x": 570, "y": 66, "text": "[3,4] · [4,3] = 24", "size": 19, "color": "correct", "w": 999},
    {"type": "text", "id": "d2", "x": 570, "y": 96, "text": "pointing the same way", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "d3", "x": 570, "y": 134, "text": "[3,4] · [−4,3] = 0", "size": 19, "color": "error", "w": 999},
    {"type": "text", "id": "d4", "x": 570, "y": 164, "text": "at right angles — unrelated", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2", "x": 570, "y": 204, "text": "multiply the matching numbers, add them up", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 672, "y": 240},
    {"type": "text", "id": "t3", "x": 824, "y": 244, "text": "every recommendation, every", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 824, "y": 268, "text": "attention weight — is this", "size": 15, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 240, "text": "the dot product", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 240, "w": 280, "text": "“similar”, made of arithmetic."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "now describe an action on every arrow at once.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-matrices-linear-transformations.mdx": {
  "id": "cover-w11m2",
  "alt": "A matrix is not a spreadsheet but an action on every arrow at once, and its columns say where the basis arrows land.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "sheet", "x": 70, "y": 44, "w": 200, "h": 52, "label": "“a grid of numbers”", "size": 14, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 200, "h": 52, "style": "strike"},
    {"type": "text", "id": "t1", "x": 176, "y": 128, "text": "not a spreadsheet —", "size": 16, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 176, "y": 156, "text": "an ACTION", "size": 19, "color": "correct", "w": 999},
    {"type": "text", "id": "t1c", "x": 176, "y": 194, "text": "it moves every arrow at once:", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1d", "x": 176, "y": 216, "text": "rotate · stretch · squash · flip", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "text", "id": "c1", "x": 560, "y": 68, "text": "read it by its columns:", "size": 16, "color": "note", "w": 999},
    {"type": "text", "id": "c2", "x": 560, "y": 100, "text": "they say where [1,0] and [0,1] land", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "c3", "x": 560, "y": 138, "text": "and every other arrow is built", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "c4", "x": 560, "y": 160, "text": "from those two ✓", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 196},
    {"type": "text", "id": "t3", "x": 858, "y": 208, "text": "multiply two = do one, then the other", "size": 15, "color": "structure", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 232, "text": "so order matters, and the shapes", "size": 15, "color": "structure", "w": 999},
    {"type": "text", "id": "t3c", "x": 858, "y": 254, "text": "must line up", "size": 15, "color": "structure", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 254, "text": "the transformation", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 250, "w": 280, "text": "every neural network layer is one of these."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and hidden inside, a few directions never turn.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-eigen-decomposition-svd-pca.mdx": {
  "id": "cover-w11m3",
  "alt": "Stretching turns almost every arrow except a few that only lengthen; keeping the strongest directions and dropping the rest is compression, and SVD works on every matrix.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 62, "text": "stretch a sheet of arrows —", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 86, "text": "almost every one swings", "size": 16, "w": 999},
    {"type": "text", "id": "t1c", "x": 194, "y": 126, "text": "almost.", "size": 18, "color": "note", "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 164, "text": "a few do not turn at all —", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t1e", "x": 190, "y": 186, "text": "they only get longer or shorter", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "bar", "id": "e1", "x": 500, "y": 52, "w": 180, "h": 18, "label": "direction 1", "value": "most of it", "color": "correct"},
    {"type": "bar", "id": "e2", "x": 500, "y": 88, "w": 90,  "h": 18, "label": "direction 2", "value": "some", "color": "note"},
    {"type": "bar", "id": "e3", "x": 500, "y": 124, "w": 16,  "h": 18, "label": "the rest", "value": "≈ nothing", "color": "muted"},
    {"type": "text", "id": "t2", "x": 560, "y": 178, "text": "keep the strong ones, drop the rest —", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 560, "y": 200, "text": "and you keep nearly all the behaviour", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 232},
    {"type": "text", "id": "t3", "x": 858, "y": 244, "text": "SVD does it for EVERY matrix —", "size": 15, "color": "structure", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 268, "text": "not only the tidy square ones", "size": 15, "color": "structure", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "eigenvectors", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 244, "w": 280, "text": "the same idea as the shadow on the wall in Week 18."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "all of that describes. Learning means changing.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-calculus-the-chain-rule.mdx": {
  "id": "cover-w11m4",
  "alt": "A derivative is how steep a hill is at one point; the chain rule multiplies along a chain, so two times three is six.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 62, "text": "how steep is this hill,", "size": 17, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 88, "text": "exactly where I am standing?", "size": 17, "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 130, "text": "flat → zero", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 152, "text": "steep climb → a big number", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1e", "x": 190, "y": 174, "text": "going down → negative", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1f", "x": 190, "y": 212, "text": "that is all a derivative is", "size": 16, "color": "correct", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 420, "y": 62},
    {"type": "text", "id": "c1", "x": 590, "y": 66, "text": "a changes b twice as fast", "size": 16, "w": 999},
    {"type": "text", "id": "c2", "x": 590, "y": 94, "text": "b changes c three times as fast", "size": 16, "w": 999},
    {"type": "text", "id": "c3", "x": 594, "y": 134, "text": "so a changes c  2 × 3 = 6", "size": 19, "color": "correct", "w": 999},
    {"type": "text", "id": "t2", "x": 590, "y": 178, "text": "multiply along the chain. That is the rule.", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 668, "y": 222},
    {"type": "text", "id": "t3", "x": 820, "y": 226, "text": "not a footnote — it is how blame", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 820, "y": 250, "text": "travels back through the layers", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 820, "y": 272, "text": "of a network in Week 21", "size": 15, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the chain rule", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 244, "w": 280, "text": "five rules are all you need. There is no sixth."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "now step downhill — and watch it go wrong.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-optimization.mdx": {
  "id": "cover-w11m5",
  "alt": "A ball rolls to the bottom of a bowl; too large a step climbs out to infinity, too small crawls, and a long narrow valley makes plain descent zig-zag.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t1", "x": 190, "y": 62, "text": "put a ball in a bowl", "size": 17, "w": 999},
    {"type": "text", "id": "t1b", "x": 190, "y": 88, "text": "and let go", "size": 17, "w": 999},
    {"type": "text", "id": "t1c", "x": 190, "y": 130, "text": "the bowl is the function:", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1d", "x": 190, "y": 152, "text": "high = bad, low = good", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1e", "x": 190, "y": 190, "text": "look at the slope · step · repeat", "size": 16, "color": "correct", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 420, "y": 62},
    {"type": "box", "id": "big", "x": 445, "y": 44, "w": 210, "h": 40, "label": "steps too big → infinity", "size": 13, "color": "error"},
    {"type": "box", "id": "small", "x": 445, "y": 94, "w": 210, "h": 40, "label": "too small → you give up", "size": 13, "color": "structure"},
    {"type": "box", "id": "right", "x": 445, "y": 144, "w": 210, "h": 40, "label": "in between → it settles ✓", "size": 13, "color": "correct"},
    {"type": "text", "id": "t2", "x": 550, "y": 214, "text": "and for a simple curve you can compute", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2b", "x": 550, "y": 236, "text": "exactly where the boundary sits", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "text", "id": "t3", "x": 856, "y": 76, "text": "in two dimensions: a long", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 856, "y": 100, "text": "narrow valley makes it zig-zag", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 856, "y": 124, "text": "from wall to wall", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3d", "x": 856, "y": 164, "text": "which is precisely what momentum", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3e", "x": 856, "y": 186, "text": "in Week 21 exists to fix", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "the step size", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 244, "w": 280, "text": "break it on purpose — that is where the intuition comes from."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "all of this was definite. The world is not.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w11")
