#!/usr/bin/env python3
"""Week-20 covers."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p3/week-20/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w20",
  "alt": "The week's journey: turning words and scales into usable numbers, unpacking timestamps and text, keeping only the columns that matter, handling rare positives, and shipping features that do not skew.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "“London”", "size": 16, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "words → numbers", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "23:41", "size": 17, "color": "correct"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "one column, twelve facts", "size": 15, "color": "muted", "w": 160},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "keep 40", "size": 17, "color": "note"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "of your 400 columns", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "0.3%", "size": 17, "color": "error"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "the rare, valuable class", "size": 15, "color": "muted", "w": 160},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "pipelines", "size": 15, "color": "structure"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "same code, both times", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 290, "y": 178, "w": 420, "h": 58, "label": "where most of the real work lives", "size": 18, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 20", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "real data does not arrive as tidy numbers."},
    {"type": "text", "id": "dq", "x": 650, "y": 306, "text": "it starts with a model that cannot read the word “London”…", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-numerical-categorical-features.mdx": {
  "id": "cover-w20m1",
  "alt": "Numbering cities 1 2 3 invents an ordering and is crossed out; one column per city is honest; and unscaled salary dominates age purely because of its units.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "bad", "x": 70, "y": 44, "w": 220, "h": 50, "label": "London=1 · Birmingham=2 · Cardiff=3", "size": 11, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 220, "h": 50, "style": "strike"},
    {"type": "text", "id": "t1", "x": 180, "y": 124, "text": "says Birmingham sits halfway", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 180, "y": 146, "text": "between London and Cardiff", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1c", "x": 180, "y": 184, "text": "one column per city instead ✓", "size": 16, "color": "correct", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "bar", "id": "a1", "x": 490, "y": 52, "w": 14,  "h": 18, "label": "age 18–90", "value": "contributes 4", "color": "structure"},
    {"type": "bar", "id": "a2", "x": 490, "y": 92, "w": 250, "h": 18, "label": "salary 20k–200k", "value": "contributes 4,000", "color": "error"},
    {"type": "text", "id": "t2", "x": 540, "y": 146, "text": "1,000× more important —", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2b", "x": 540, "y": 168, "text": "because of the units, nothing else", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2c", "x": 540, "y": 204, "text": "scale them and they compete fairly ✓", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 232},
    {"type": "text", "id": "t3", "x": 858, "y": 244, "text": "5,000 categories? one column each", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 268, "text": "is hopeless — target/hash encode", "size": 15, "color": "correct", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "encoding · scaling", "ring": "note"},
    {"type": "note", "id": "n", "x": 340, "y": 244, "w": 290, "text": "fit every transform inside the pipeline, or it leaks."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "now the hard columns: a timestamp, and a paragraph.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-temporal-text-interaction-features.mdx": {
  "id": "cover-w20m2",
  "alt": "A timestamp unpacks into weekday, hour, days since last order and days to renewal; hours are circular so 23 sits next to 0; and price relative to income is the real signal.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "ts", "x": 70, "y": 44, "w": 220, "h": 46, "label": "2026-09-04 23:41", "size": 16, "color": "structure"},
    {"type": "text", "id": "t1", "x": 180, "y": 116, "text": "Friday · nearly midnight ·", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t1b", "x": 180, "y": 138, "text": "4 days after payday ·", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t1c", "x": 180, "y": 160, "text": "90 min since the last order ·", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t1d", "x": 180, "y": 182, "text": "14 days to renewal", "size": 15, "color": "correct", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "text", "id": "c1", "x": 540, "y": 72, "text": "hour 23 and hour 0", "size": 16, "w": 999},
    {"type": "text", "id": "c2", "x": 540, "y": 96, "text": "are next to each other —", "size": 16, "w": 999},
    {"type": "text", "id": "c3", "x": 540, "y": 120, "text": "as plain numbers they look", "size": 16, "color": "error", "w": 999},
    {"type": "text", "id": "c4", "x": 540, "y": 142, "text": "maximally far apart", "size": 16, "color": "error", "w": 999},
    {"type": "text", "id": "c5", "x": 540, "y": 180, "text": "time is a circle — encode it as one", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 210},
    {"type": "text", "id": "i1", "x": 850, "y": 222, "text": "price: fine.  income: fine.", "size": 16, "color": "muted", "w": 999},
    {"type": "text", "id": "i2", "x": 850, "y": 248, "text": "price ÷ income: the model", "size": 17, "color": "note", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "feature engineering", "ring": "note"},
    {"type": "note", "id": "n", "x": 350, "y": 226, "w": 290, "text": "text works with counts long before it needs a language model."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "400 columns later, which forty actually matter?", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-feature-selection-dimensionality.mdx": {
  "id": "cover-w20m3",
  "alt": "Four hundred columns slow serving and help a model memorise noise; two near-identical columns split their importance so both look worthless; removing and measuring is the honest test.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "bar", "id": "c1", "x": 130, "y": 52, "w": 160, "h": 20, "label": "400", "value": "columns made", "color": "error"},
    {"type": "bar", "id": "c2", "x": 130, "y": 92, "w": 30,  "h": 20, "label": "40", "value": "that matter", "color": "correct"},
    {"type": "text", "id": "t1", "x": 200, "y": 148, "text": "redundant columns are not free:", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1b", "x": 200, "y": 170, "text": "slower · harder to explain ·", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1c", "x": 200, "y": 192, "text": "more ways to memorise noise", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 108},
    {"type": "box", "id": "d1", "x": 450, "y": 44, "w": 180, "h": 38, "label": "column A", "size": 14, "color": "note"},
    {"type": "box", "id": "d2", "x": 450, "y": 90, "w": 180, "h": 38, "label": "column A′ (near identical)", "size": 11, "color": "note"},
    {"type": "text", "id": "t2", "x": 540, "y": 158, "text": "importance splits between them —", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2b", "x": 540, "y": 180, "text": "both look worthless, you delete both,", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2c", "x": 540, "y": 204, "text": "and the signal is gone", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 236},
    {"type": "text", "id": "t3", "x": 858, "y": 248, "text": "the honest test: remove it,", "size": 16, "color": "correct", "w": 999},
    {"type": "text", "id": "t3b", "x": 858, "y": 272, "text": "and measure what happens", "size": 16, "color": "correct", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "feature selection", "ring": "note"},
    {"type": "note", "id": "n", "x": 330, "y": 250, "w": 280, "text": "every feature kept is one you serve and maintain forever."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and your target column is 0.3% positives.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-imbalanced-classification.mdx": {
  "id": "cover-w20m4",
  "alt": "Three positives in a thousand rows; oversampling changes the base rate and breaks calibration; class weights and moving the threshold are the reliable wins.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 96},
    {"type": "text", "id": "t1", "x": 192, "y": 60, "text": "fraud · equipment failure ·", "size": 16, "w": 999},
    {"type": "text", "id": "t1b", "x": 192, "y": 84, "text": "the tumour · the leaver", "size": 16, "w": 999},
    {"type": "text", "id": "t1c", "x": 180, "y": 126, "text": "if it happened half the time,", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1d", "x": 180, "y": 148, "text": "you would not need a model", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t1e", "x": 180, "y": 186, "text": "3 positives per 1,000 rows", "size": 17, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "sm", "x": 425, "y": 44, "w": 220, "h": 46, "label": "oversample / SMOTE", "size": 15, "color": "note"},
    {"type": "text", "id": "t2", "x": 535, "y": 118, "text": "you changed the base rate —", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2b", "x": 535, "y": 140, "text": "so “0.8” no longer means 80%", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2c", "x": 535, "y": 178, "text": "every downstream cost", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2d", "x": 535, "y": 200, "text": "calculation is now wrong", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 700, "y": 62},
    {"type": "box", "id": "w", "x": 725, "y": 44, "w": 230, "h": 42, "label": "class weights", "size": 15, "color": "correct"},
    {"type": "box", "id": "th", "x": 725, "y": 96, "w": 230, "h": 42, "label": "move the threshold", "size": 15, "color": "correct"},
    {"type": "text", "id": "t3", "x": 840, "y": 168, "text": "costs nothing · breaks nothing", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t3b", "x": 840, "y": 190, "text": "and it is where the win is", "size": 15, "color": "correct", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "class imbalance", "ring": "note"},
    {"type": "note", "id": "n", "x": 350, "y": 244, "w": 290, "text": "the problems worth solving are almost always rare."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "all true in a notebook. Production is another matter.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-production-feature-pipelines.mdx": {
  "id": "cover-w20m5",
  "alt": "The same feature computed twice disagrees; the rule is to compute it once and use that code both times; and every training row must use only data that existed at that moment.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "tr", "x": 70, "y": 44, "w": 210, "h": 44, "label": "training: mean(all orders)", "size": 13, "color": "structure"},
    {"type": "box", "id": "sv", "x": 70, "y": 96, "w": 210, "h": 44, "label": "serving: mean(incl. cancelled)", "size": 12, "color": "error"},
    {"type": "text", "id": "t1", "x": 176, "y": 172, "text": "same name · different meaning ·", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 176, "y": 194, "text": "nothing fails loudly", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "once", "x": 405, "y": 44, "w": 240, "h": 56, "label": "compute it once, in one place", "size": 14, "color": "correct"},
    {"type": "text", "id": "t2", "x": 525, "y": 130, "text": "and use that same code for", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 525, "y": 152, "text": "training and for serving", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2c", "x": 525, "y": 190, "text": "a rule, not a tool", "size": 16, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "text", "id": "t3", "x": 850, "y": 76, "text": "every training row uses only", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 850, "y": 98, "text": "data that existed at that moment", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 850, "y": 136, "text": "break that and you have rebuilt", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3d", "x": 850, "y": 158, "text": "Week 19's leakage — distributed", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t3e", "x": 850, "y": 196, "text": "features need tests and monitoring", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 200, "y": 250, "text": "training/serving skew", "ring": "note"},
    {"type": "note", "id": "n", "x": 360, "y": 244, "w": 300, "text": "the most common way a good model dies quietly."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "but how do you engineer features for a photograph?", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w20")
