#!/usr/bin/env python3
"""Week-30 covers."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from covers_lib import build, preview
W = "curriculum/p4/week-30/"
COVERS = {
W+"index.mdx": {
  "id": "cover-w30",
  "alt": "The week's journey: draw the work as a graph, choose how many workers, save progress so a crash resumes, put hard edges on spend, and design a system people will run.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 55, "y": 60},
    {"type": "box", "id": "s1", "x": 80, "y": 40, "w": 120, "h": 60, "label": "the graph", "size": 17, "color": "structure"},
    {"type": "text", "id": "t1", "x": 140, "y": 126, "text": "work is not a list", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b2", "n": 2, "x": 250, "y": 60},
    {"type": "box", "id": "s2", "x": 275, "y": 40, "w": 115, "h": 60, "label": "how many?", "size": 15, "color": "note"},
    {"type": "text", "id": "t2", "x": 332, "y": 126, "text": "team or generalist", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b3", "n": 3, "x": 440, "y": 60},
    {"type": "box", "id": "s3", "x": 465, "y": 40, "w": 115, "h": 60, "label": "resume", "size": 17, "color": "correct"},
    {"type": "text", "id": "t3", "x": 522, "y": 126, "text": "survive 3 a.m.", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b4", "n": 4, "x": 630, "y": 60},
    {"type": "box", "id": "s4", "x": 655, "y": 40, "w": 115, "h": 60, "label": "budgets", "size": 17, "color": "error"},
    {"type": "text", "id": "t4", "x": 712, "y": 126, "text": "survive success", "size": 15, "color": "muted", "w": 150},
    {"type": "badge", "id": "b5", "n": 5, "x": 820, "y": 60},
    {"type": "box", "id": "s5", "x": 845, "y": 40, "w": 115, "h": 60, "label": "design", "size": 17, "color": "structure"},
    {"type": "text", "id": "t5", "x": 902, "y": 126, "text": "who carries the pager", "size": 15, "color": "muted", "w": 160},
    {"type": "box", "id": "res", "x": 300, "y": 178, "w": 400, "h": 58, "label": "a system other people will run", "size": 18, "color": "correct", "fill": "hachure", "fill_gap": 15},
    {"type": "circled", "id": "term", "x": 150, "y": 205, "text": "week 30", "ring": "note"},
    {"type": "note", "id": "n", "x": 730, "y": 190, "w": 240, "text": "one worker becomes a system that survives failure."},
    {"type": "text", "id": "dq", "x": 660, "y": 306, "text": "it starts with a job that was never really a list…", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 370, 300)},

W+"1-graphs-as-the-right-abstraction.mdx": {
  "id": "cover-w30m1",
  "alt": "A to-do list forces false ordering and is crossed out; the same work as a graph runs three researches in parallel; the graph's state is what makes resuming possible.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "l", "x": 70, "y": 44, "w": 190, "h": 86, "label": "1. research A 2. research B 3. research C 4. draft…", "size": 12, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 190, "h": 86, "style": "strike"},
    {"type": "text", "id": "t1", "x": 168, "y": 162, "text": "a list invents an order", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 168, "y": 184, "text": "the work never had", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 350, "y": 62},
    {"type": "box", "id": "n1", "x": 380, "y": 42, "w": 96, "h": 34, "label": "research A", "size": 12, "color": "correct"},
    {"type": "box", "id": "n2", "x": 380, "y": 86, "w": 96, "h": 34, "label": "research B", "size": 12, "color": "correct"},
    {"type": "box", "id": "n3", "x": 380, "y": 130, "w": 96, "h": 34, "label": "research C", "size": 12, "color": "correct"},
    {"type": "box", "id": "n4", "x": 520, "y": 86, "w": 90, "h": 34, "label": "draft", "size": 13, "color": "structure"},
    {"type": "line", "id": "e1", "x1": 478, "y1": 60, "x2": 518, "y2": 98, "color": "muted", "width": 2.5},
    {"type": "line", "id": "e2", "x1": 478, "y1": 103, "x2": 518, "y2": 103, "color": "muted", "width": 2.5},
    {"type": "line", "id": "e3", "x1": 478, "y1": 147, "x2": 518, "y2": 110, "color": "muted", "width": 2.5},
    {"type": "text", "id": "t2", "x": 495, "y": 196, "text": "the arrows are the truth — these three run at once", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "text", "id": "g1", "x": 850, "y": 76, "text": "free parallelism", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "g2", "x": 850, "y": 106, "text": "a state you can inspect", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "g3", "x": 838, "y": 136, "text": "and, at 3 a.m., a record", "size": 17, "color": "correct", "w": 999},
    {"type": "text", "id": "g4", "x": 838, "y": 158, "text": "of what already finished", "size": 17, "color": "correct", "w": 999},
    {"type": "circled", "id": "term", "x": 230, "y": 248, "text": "the work as a graph", "ring": "note"},
    {"type": "note", "id": "n", "x": 430, "y": 240, "w": 340, "text": "dependencies are the truth; ordering is just one flattening of them."},
    {"type": "text", "id": "dq", "x": 640, "y": 306, "text": "now: who does each node? One worker, or a team?", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"2-multi-agent-patterns.mdx": {
  "id": "cover-w30m2",
  "alt": "A four-agent company chats 20 turns and is crossed out; one agent does the same work in four; specialists win only when tools, prompts or models genuinely differ.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "ellipse", "id": "a1", "cx": 110, "cy": 70, "rx": 40, "ry": 20, "label": "manager", "color": "note"},
    {"type": "ellipse", "id": "a2", "cx": 210, "cy": 60, "rx": 42, "ry": 20, "label": "researcher", "color": "note"},
    {"type": "ellipse", "id": "a3", "cx": 120, "cy": 128, "rx": 36, "ry": 20, "label": "writer", "color": "note"},
    {"type": "ellipse", "id": "a4", "cx": 220, "cy": 130, "rx": 34, "ry": 20, "label": "critic", "color": "note"},
    {"type": "text", "id": "t1", "x": 168, "y": 186, "text": "20 turns · every handoff is tiles", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 360, "y": 62},
    {"type": "box", "id": "one", "x": 385, "y": 44, "w": 200, "h": 56, "label": "one agent · 4 turns", "size": 16, "color": "correct"},
    {"type": "text", "id": "t2", "x": 485, "y": 128, "text": "same output, a quarter of the bill", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 485, "y": 160, "text": "and far fewer chances to go wrong", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 680, "y": 62},
    {"type": "text", "id": "w1", "x": 845, "y": 76, "text": "a team wins only when the jobs", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "w2", "x": 845, "y": 100, "text": "need different tools, prompts", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "w3", "x": 845, "y": 124, "text": "or different models", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "w4", "x": 845, "y": 162, "text": "the patterns that ship minimise", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "w5", "x": 845, "y": 184, "text": "conversation, not celebrate it", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 220, "y": 246, "text": "multi-agent", "ring": "note"},
    {"type": "note", "id": "n", "x": 400, "y": 226, "w": 320, "text": "a meeting that could have been an email costs the same either way."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "then node 7 of 9 dies, ninety minutes in.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"3-durable-execution-checkpoint-resume.mdx": {
  "id": "cover-w30m3",
  "alt": "Node seven dies; restarting from node one repeats six paid steps and is crossed out; resuming from the saved state picks up at seven; idempotency keys stop the second send.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "text", "id": "t0", "x": 190, "y": 56, "text": "9 nodes · 2 hours · real money", "size": 15, "color": "muted", "w": 999},
    {"type": "box", "id": "run", "x": 70, "y": 72, "w": 220, "h": 46, "label": "node 7 dies at 3 a.m.", "size": 15, "color": "error"},
    {"type": "box", "id": "rs", "x": 70, "y": 132, "w": 220, "h": 46, "label": "restart from node 1", "size": 15, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 132, "w": 220, "h": 46, "style": "strike"},
    {"type": "text", "id": "t1", "x": 180, "y": 206, "text": "six paid steps, done twice", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 380, "y": 62},
    {"type": "box", "id": "save", "x": 405, "y": 44, "w": 220, "h": 56, "label": "the save file: node results", "size": 14, "color": "correct"},
    {"type": "text", "id": "t2", "x": 515, "y": 130, "text": "resume skips 1–6, restarts at 7 ✓", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 515, "y": 164, "text": "it saves the graph's state,", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t2c", "x": 515, "y": 186, "text": "not the model's memory", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "box", "id": "send", "x": 715, "y": 44, "w": 240, "h": 50, "label": "send_invoice(key: 8f21)", "size": 14, "color": "note"},
    {"type": "text", "id": "t3", "x": 828, "y": 124, "text": "the second attempt sees", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3b", "x": 828, "y": 146, "text": "the first, and does nothing", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t3c", "x": 835, "y": 180, "text": "otherwise: six emails, twice", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 230, "y": 250, "text": "durable execution", "ring": "note"},
    {"type": "note", "id": "n", "x": 430, "y": 244, "w": 330, "text": "every long game has a save system, for an obvious reason."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "crashes are loud. Runaway loops are quiet and expensive.", "size": 18, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"4-resilience-budgets-failure-handling.mdx": {
  "id": "cover-w30m4",
  "alt": "An unbounded loop spends four hundred pounds and is crossed out; four hard edges cap tiles, turns, time and money; backoff and a circuit breaker stop the retry storm.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 62},
    {"type": "box", "id": "loop", "x": 70, "y": 44, "w": 210, "h": 56, "label": "200,000 turns · £400", "size": 16, "color": "error"},
    {"type": "crossout", "id": "x", "x": 70, "y": 44, "w": 210, "h": 56, "style": "strike"},
    {"type": "text", "id": "t1", "x": 175, "y": 130, "text": "nobody was watching —", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t1b", "x": 175, "y": 152, "text": "it was Tuesday afternoon", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 350, "y": 62},
    {"type": "box", "id": "e1", "x": 375, "y": 40, "w": 105, "h": 38, "label": "tile budget", "size": 13, "color": "correct"},
    {"type": "box", "id": "e2", "x": 490, "y": 40, "w": 105, "h": 38, "label": "turn limit", "size": 13, "color": "correct"},
    {"type": "box", "id": "e3", "x": 375, "y": 88, "w": 105, "h": 38, "label": "wall clock", "size": 13, "color": "correct"},
    {"type": "box", "id": "e4", "x": 490, "y": 88, "w": 105, "h": 38, "label": "spend cap", "size": 13, "color": "correct"},
    {"type": "text", "id": "t2", "x": 485, "y": 156, "text": "enforced in code — never in the prompt", "size": 15, "color": "correct", "w": 999},
    {"type": "text", "id": "t2b", "x": 485, "y": 186, "text": "spent budget → return the partial result, honestly", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "text", "id": "r1", "x": 850, "y": 76, "text": "back off exponentially", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "r2", "x": 850, "y": 104, "text": "break the circuit", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "r3", "x": 850, "y": 132, "text": "degrade, and say so", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "r4", "x": 850, "y": 170, "text": "naive retrying turns one slow", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "r5", "x": 850, "y": 192, "text": "dependency into an outage", "size": 15, "color": "error", "w": 999},
    {"type": "circled", "id": "term", "x": 220, "y": 246, "text": "hard edges", "ring": "note"},
    {"type": "note", "id": "n", "x": 400, "y": 232, "w": 330, "text": "a system with no limit will consume everything you give it."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "all the parts work. Now: where does a human belong?", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},

W+"5-architecting-a-real-agentic-system.mdx": {
  "id": "cover-w30m5",
  "alt": "The design review asks about approval gates, blast radius, bad-day cost and the runbook; agents belong only where the steps cannot be enumerated.",
  "elements": [
    {"type": "badge", "id": "b1", "n": 1, "x": 48, "y": 92},
    {"type": "text", "id": "q1", "x": 200, "y": 58, "text": "“where does a human approve?”", "size": 15, "w": 999},
    {"type": "text", "id": "q2", "x": 200, "y": 86, "text": "“what is the worst it can do?”", "size": 15, "w": 999},
    {"type": "text", "id": "q3", "x": 200, "y": 114, "text": "“what does a bad day cost?”", "size": 15, "w": 999},
    {"type": "text", "id": "q4", "x": 200, "y": 142, "text": "“who fixes it at 3 a.m.?”", "size": 15, "w": 999},
    {"type": "text", "id": "t1", "x": 180, "y": 186, "text": "nobody asks which framework", "size": 15, "color": "muted", "w": 999},
    {"type": "badge", "id": "b2", "n": 2, "x": 400, "y": 62},
    {"type": "box", "id": "gate", "x": 425, "y": 44, "w": 210, "h": 56, "label": "approval gate", "size": 16, "color": "note"},
    {"type": "text", "id": "t2", "x": 530, "y": 128, "text": "expensive · irreversible · public", "size": 15, "color": "note", "w": 999},
    {"type": "text", "id": "t2b", "x": 530, "y": 162, "text": "a gate nobody reads is worse", "size": 15, "color": "error", "w": 999},
    {"type": "text", "id": "t2c", "x": 530, "y": 184, "text": "than no gate at all", "size": 15, "color": "error", "w": 999},
    {"type": "badge", "id": "b3", "n": 3, "x": 690, "y": 62},
    {"type": "box", "id": "no", "x": 715, "y": 44, "w": 240, "h": 66, "label": "deterministic · high-volume · legally binding", "size": 12, "color": "structure"},
    {"type": "text", "id": "t3", "x": 828, "y": 138, "text": "these stay ordinary software", "size": 16, "color": "structure", "w": 999},
    {"type": "text", "id": "t3b", "x": 835, "y": 172, "text": "an agent is for the steps you", "size": 15, "color": "muted", "w": 999},
    {"type": "text", "id": "t3c", "x": 835, "y": 194, "text": "genuinely cannot enumerate", "size": 15, "color": "muted", "w": 999},
    {"type": "circled", "id": "term", "x": 220, "y": 246, "text": "blast radius", "ring": "note"},
    {"type": "note", "id": "n", "x": 400, "y": 236, "w": 330, "text": "a system is defined by its edges, not its cleverness."},
    {"type": "text", "id": "dq", "x": 620, "y": 306, "text": "and how would you know it is any good? Week 31.", "size": 19, "color": "note"},
  ], "arrow": (150, 300, 340, 300)},
}
if __name__ == "__main__":
    build(COVERS)
    if "--preview" in sys.argv: preview(COVERS, "w30")
