#!/usr/bin/env python3
"""Cover sketches for week-25 chapters: a small, lightly animated, text-free
drawing at the very top of the page that teases the story without spoiling the
mechanism. Inlined (CDN strips SMIL); no embedded font needed. Idempotent via
HERO markers."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DUR = 8.0

def anim(attr, pts, extra=""):
    kt = ";".join(f"{t/DUR:.4f}" for t,_ in pts)
    kv = ";".join(str(v) for _,v in pts)
    return (f'<animate attributeName="{attr}" dur="{DUR}s" repeatCount="indefinite" '
            f'keyTimes="{kt}" values="{kv}" {extra}/>')

def slide_x(pts):
    kt = ";".join(f"{t/DUR:.4f}" for t,_ in pts)
    kv = ";".join(f"{x} 0" for _,x in pts)
    return (f'<animateTransform attributeName="transform" type="translate" dur="{DUR}s" '
            f'repeatCount="indefinite" keyTimes="{kt}" values="{kv}"/>')

def door_hero(ink, accent, red, bg):
    """A note with scribbled writing slides under a locked door; a reply with a
    red cross slides back. The whole strawberry story in eight silent seconds."""
    scribble = "".join(
        f'<path d="M18 {y} q 14 -5 28 0 q 14 5 28 0" fill="none" stroke="{ink}" stroke-width="2.5"/>'
        for y in (16, 26, 36))
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 200" width="1000" height="200" role="img" aria-label="A note slides under a locked door; a reply comes back marked with a red cross.">
  <rect width="1000" height="200" rx="8" fill="{bg}"/>
  <g>
    <rect x="620" y="20" width="150" height="160" rx="5" fill="none" stroke="{ink}" stroke-width="4" transform="rotate(0.8 695 100)"/>
    <circle cx="745" cy="105" r="6" fill="none" stroke="{ink}" stroke-width="3"/>
    <rect x="645" y="152" width="100" height="16" rx="5" fill="{accent}" fill-opacity="0.15" stroke="{accent}" stroke-width="3"/>
  </g>
  <g opacity="0">
    <g>
      <rect x="0" y="0" width="90" height="52" rx="4" fill="{bg}" stroke="{ink}" stroke-width="3" transform="rotate(-2)"/>
      {scribble}
      {slide_x([(0,120),(0.6,120),(2.6,568),(DUR,568)])}
    </g>
    {anim("opacity",[(0,0),(0.5,0),(0.9,1),(2.2,1),(2.8,0),(DUR,0)])}
  </g>
  <g opacity="0">
    <g>
      <rect x="0" y="0" width="90" height="52" rx="4" fill="{bg}" stroke="{ink}" stroke-width="3" transform="rotate(1.5)"/>
      <path d="M30 14 L60 40 M60 14 L30 40" stroke="{red}" stroke-width="5" fill="none"/>
      {slide_x([(0,568),(3.6,568),(5.6,150),(DUR,150)])}
    </g>
    {anim("opacity",[(0,0),(3.6,0),(4.0,1),(6.8,1),(7.4,0),(DUR,0)])}
  </g>
</svg>'''

def map_hero(ink, a, b, c, bg):
    """Pins cluster on a wall map; one more pin drops in beside its friends."""
    pins = "".join(f'<circle cx="{x}" cy="{y}" r="8" fill="{col}"/>'
        for x,y,col in [(330,80,a),(390,110,a),(700,70,b),(760,140,c)])
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 200" width="1000" height="200" role="img" aria-label="Pins cluster on a wall map; a new pin drops in beside its neighbours.">
  <rect width="1000" height="200" rx="8" fill="{bg}"/>
  <rect x="120" y="25" width="760" height="150" rx="8" fill="none" stroke="{ink}" stroke-width="3" stroke-dasharray="5 7" transform="rotate(-0.4 500 100)"/>
  {pins}
  <g opacity="0">
    <circle cx="355" cy="135" r="8" fill="{a}">
      <animate attributeName="cy" dur="8s" repeatCount="indefinite" keyTimes="0;0.25;0.36;1" values="-20;-20;135;135" calcMode="spline" keySplines="0 0 1 1;0.3 0 0.2 1;0 0 1 1"/>
    </circle>
    <animate attributeName="opacity" dur="8s" repeatCount="indefinite" keyTimes="0;0.22;0.28;0.93;1" values="0;0;1;1;0"/>
  </g>
  <g opacity="0">
    <line x1="338" y1="88" x2="384" y2="104" stroke="{a}" stroke-width="3" stroke-dasharray="6 5"/>
    <line x1="362" y1="128" x2="386" y2="116" stroke="{a}" stroke-width="3" stroke-dasharray="6 5"/>
    <animate attributeName="opacity" dur="8s" repeatCount="indefinite" keyTimes="0;0.42;0.5;0.93;1" values="0;0;1;1;0"/>
  </g>
</svg>'''

BEGIN, END = "{/* HERO:BEGIN generated by tools/heroes_w25.py */}", "{/* HERO:END */}"
def inline(slug, light, dark):
    block = (f"{BEGIN}\n<Frame>\n  <div className=\"block dark:hidden w-full\">\n    {light}\n  </div>"
             f"\n  <div className=\"hidden dark:block w-full\">\n    {dark}\n  </div>\n</Frame>\n{END}")
    p = ROOT / slug; t = p.read_text()
    if BEGIN in t:
        t = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, t, flags=re.S)
    else:
        i = t.index("<Note>")
        t = t[:i] + block + "\n\n" + t[i:]
    p.write_text(t); print("hero inlined:", slug)

inline("curriculum/p4/week-25/1-text-tokens.mdx",
       door_hero("#1e1e1e", "#2f9e44", "#e03131", "#fffdf7"),
       door_hero("#e8e6e3", "#6cc47a", "#ff8787", "#1a1a1a"))
inline("curriculum/p4/week-25/2-embeddings-positional-information.mdx",
       map_hero("#6b6b6b", "#0ca678", "#e8590c", "#1971c2", "#fffdf7"),
       map_hero("#9a9791", "#12b886", "#ffa94d", "#4dabf7", "#1a1a1a"))
